"""
CS1-EXP1: word + character TF-IDF with class-weighted SGD Logistic Regression.

    normalized C/C++ function text
        -> word TF-IDF, n-grams (1, 3)
        +  character TF-IDF, n-grams (3, 4)
        -> sparse feature union
        -> class-weighted L2 Logistic Regression trained with SGD

Evaluation protocol
--------------------
5-fold project-grouped, stratified CV; every fold takes a turn as the test
set (no separate fixed holdout). For each outer fold, TF-IDF capacity
(word/char max_features, word/char min_df), the SGD L2 penalty (alpha), and
the decision threshold are all selected via 3-fold inner CV on that outer
fold's training projects only, then the winning configuration is refit on
the full outer-training partition and scored once on the untouched outer
test fold. Reported metrics are mean +/- std across the 5 outer folds.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import gc
import itertools
import json
from pathlib import Path
import time
import warnings
from typing import Mapping, Optional, Sequence

import numpy as np
import pandas as pd
from scipy.sparse import hstack
from sklearn.exceptions import ConvergenceWarning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedGroupKFold

from utils.evaluation import (
    EvaluationConfig,
    compute_binary_metrics,
    evaluate_oof_predictions,
    save_evaluation_artifacts,
    select_f1_threshold,
)
from utils.split_manifest import (
    SplitConfig,
    apply_manifest,
    assert_manifest_integrity,
)


EXP1_VERSION = "cs1-exp1-sgd-logistic-v3-nested-rotating-5fold"


@dataclass(frozen=True)
class Exp1Config:
    """Declared reproducible configuration for CS1-EXP1-LR, including every searched grid."""

    experiment_name: str = "cs1_exp1_lr"
    code_column: str = "normalized_code"
    source_id_column: str = "source_row_id"
    label_column: str = "label"
    project_column: str = "project"
    fold_column: str = "fold"

    n_splits: int = 5
    random_state: int = 42

    # Word TF-IDF: identifiers, API calls, and local lexical sequences.
    word_ngram_range: tuple[int, int] = (1, 3)
    word_max_df: float = 0.995
    word_max_features_grid: tuple[int, ...] = (20_000, 50_000, 80_000)
    word_min_df_grid: tuple[int, ...] = (2, 3)

    # Character TF-IDF: punctuation, pointer/array patterns, and partial tokens.
    char_analyzer: str = "char"
    char_ngram_range: tuple[int, int] = (3, 4)
    char_max_df: float = 0.995
    char_max_features_grid: tuple[int, ...] = (30_000, 60_000, 90_000)
    char_min_df_grid: tuple[int, ...] = (5, 8)

    lowercase: bool = False
    sublinear_tf: bool = True
    tfidf_norm: str = "l2"

    # SGD-based binary Logistic Regression: scalable for sparse TF-IDF.
    sgd_loss: str = "log_loss"
    sgd_penalty: str = "l2"
    sgd_alpha_grid: tuple[float, ...] = (1e-6, 3e-6, 1e-5, 3e-5, 1e-4)
    sgd_class_weight: str = "balanced"
    sgd_max_iter: int = 80
    sgd_tol: float = 1e-3
    sgd_average: bool = True

    # Inner CV used to select every grid above, per outer fold.
    inner_n_splits: int = 3
    inner_random_state: int = 20260707
    selection_metric: str = "average_precision_pr_auc"

    top_features_per_direction: int = 30
    verbose: bool = True


@dataclass(frozen=True)
class Exp1Artifacts:
    """Artifacts generated by a complete official EXP-1 run."""

    config_json: Path
    fold_training_csv: Path
    inner_search_csv: Path
    top_features_csv: Path
    run_metadata_json: Path
    evaluation_paths: object


def _log(message: str, enabled: bool = True) -> None:
    """Print an immediate timestamped progress message when verbose mode is enabled."""
    if enabled:
        timestamp = datetime.now().strftime("%H:%M:%S")
        print(f"[{timestamp}] {message}", flush=True)


def _format_seconds(seconds: float) -> str:
    """Human-readable elapsed time."""
    seconds = float(seconds)
    if seconds < 60:
        return f"{seconds:.1f}s"
    return f"{seconds / 60:.2f} min"


def _validate_config(config: Exp1Config) -> None:
    """Fail fast on an invalid configuration before any fold work starts."""
    if config.n_splits < 2:
        raise ValueError("n_splits must be >= 2.")
    if config.inner_n_splits < 2:
        raise ValueError("inner_n_splits must be >= 2.")
    if config.word_ngram_range[0] < 1 or config.word_ngram_range[1] < config.word_ngram_range[0]:
        raise ValueError("word_ngram_range must be a valid positive interval.")
    if config.char_ngram_range[0] < 1 or config.char_ngram_range[1] < config.char_ngram_range[0]:
        raise ValueError("char_ngram_range must be a valid positive interval.")
    if not config.word_max_features_grid or any(v < 1 for v in config.word_max_features_grid):
        raise ValueError("word_max_features_grid must be non-empty with values >= 1.")
    if not config.char_max_features_grid or any(v < 1 for v in config.char_max_features_grid):
        raise ValueError("char_max_features_grid must be non-empty with values >= 1.")
    if not config.word_min_df_grid or any(v < 1 for v in config.word_min_df_grid):
        raise ValueError("word_min_df_grid must be non-empty with values >= 1.")
    if not config.char_min_df_grid or any(v < 1 for v in config.char_min_df_grid):
        raise ValueError("char_min_df_grid must be non-empty with values >= 1.")
    if config.sgd_loss != "log_loss":
        raise ValueError("CS1-EXP1 requires sgd_loss='log_loss' for Logistic Regression.")
    if config.sgd_penalty != "l2":
        raise ValueError("CS1-EXP1 requires sgd_penalty='l2' for the declared baseline.")
    if not config.sgd_alpha_grid or any(a <= 0 for a in config.sgd_alpha_grid):
        raise ValueError("sgd_alpha_grid must be non-empty with values > 0.")
    if config.sgd_max_iter < 1:
        raise ValueError("sgd_max_iter must be >= 1.")
    if config.sgd_tol <= 0:
        raise ValueError("sgd_tol must be > 0.")
    if config.selection_metric != "average_precision_pr_auc":
        raise ValueError("This implementation selects every grid by pooled inner PR-AUC.")


def _require_columns(frame: pd.DataFrame, columns: Sequence[str]) -> None:
    """Raise a clear error listing any missing required column."""
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        raise KeyError(
            f"Missing required column(s): {missing}. "
            f"Available columns: {sorted(frame.columns.tolist())}"
        )


def _validate_experiment_frame(frame: pd.DataFrame, config: Exp1Config) -> pd.DataFrame:
    """Validate the normalized data after its fixed fold assignment is attached."""
    _require_columns(
        frame,
        [
            config.source_id_column,
            config.code_column,
            config.label_column,
            config.project_column,
            config.fold_column,
        ],
    )

    checked = frame.copy()

    if checked[config.source_id_column].isna().any():
        raise ValueError("source_row_id contains missing values.")
    if checked[config.source_id_column].duplicated().any():
        raise ValueError("source_row_id contains duplicate values.")

    checked[config.code_column] = checked[config.code_column].fillna("").astype(str)
    empty_code = checked[config.code_column].str.strip() == ""
    if empty_code.any():
        raise ValueError(
            f"{int(empty_code.sum()):,} rows contain empty normalized code. "
            "Use the normalized cache that passed the prior quality gate."
        )

    labels = pd.to_numeric(checked[config.label_column], errors="raise")
    if not labels.isin([0, 1]).all():
        raise ValueError("label must contain exactly binary values 0 and 1.")
    checked[config.label_column] = labels.astype("int8")

    checked[config.project_column] = (
        checked[config.project_column].fillna("").astype(str).str.strip()
    )
    if (checked[config.project_column] == "").any():
        raise ValueError("project contains missing or empty identifiers.")

    folds = pd.to_numeric(checked[config.fold_column], errors="raise").astype(int)
    expected = set(range(config.n_splits))
    observed = set(folds.unique().tolist())
    if observed != expected:
        raise ValueError(f"Expected folds {sorted(expected)}, observed {sorted(observed)}.")
    checked[config.fold_column] = folds.astype("int8")

    return checked


def _build_word_vectorizer(config: Exp1Config, max_features: int, min_df: int) -> TfidfVectorizer:
    """Word TF-IDF with a custom token pattern that retains one-character tokens such as i and x."""
    return TfidfVectorizer(
        analyzer="word",
        token_pattern=r"(?u)\b\w+\b",
        ngram_range=config.word_ngram_range,
        min_df=min_df,
        max_df=config.word_max_df,
        max_features=max_features,
        lowercase=config.lowercase,
        sublinear_tf=config.sublinear_tf,
        norm=config.tfidf_norm,
        dtype=np.float32,
    )


def _build_char_vectorizer(config: Exp1Config, max_features: int, min_df: int) -> TfidfVectorizer:
    """Character TF-IDF over raw source text, capturing pointer/array/operator patterns."""
    return TfidfVectorizer(
        analyzer=config.char_analyzer,
        ngram_range=config.char_ngram_range,
        min_df=min_df,
        max_df=config.char_max_df,
        max_features=max_features,
        lowercase=config.lowercase,
        sublinear_tf=config.sublinear_tf,
        norm=config.tfidf_norm,
        dtype=np.float32,
    )


def _build_model(config: Exp1Config, alpha: float) -> SGDClassifier:
    """Construct scalable L2 Logistic Regression trained with SGD at a given alpha."""
    return SGDClassifier(
        loss=config.sgd_loss,
        penalty=config.sgd_penalty,
        alpha=float(alpha),
        class_weight=config.sgd_class_weight,
        max_iter=config.sgd_max_iter,
        tol=config.sgd_tol,
        average=config.sgd_average,
        shuffle=True,
        random_state=config.random_state,
    )


def _vectorizer_grid(config: Exp1Config) -> list[tuple[int, int, int, int]]:
    """Every (word_max_features, char_max_features, word_min_df, char_min_df) combination."""
    return list(
        itertools.product(
            config.word_max_features_grid,
            config.char_max_features_grid,
            config.word_min_df_grid,
            config.char_min_df_grid,
        )
    )


def _fit_and_transform(
    train_code: pd.Series,
    test_code: pd.Series,
    config: Exp1Config,
    word_max_features: int,
    char_max_features: int,
    word_min_df: int,
    char_min_df: int,
):
    """Fit train-only word/char vectorizers for one combo and transform train/test code."""
    word_vectorizer = _build_word_vectorizer(config, word_max_features, word_min_df)
    char_vectorizer = _build_char_vectorizer(config, char_max_features, char_min_df)

    x_train_word = word_vectorizer.fit_transform(train_code)
    x_test_word = word_vectorizer.transform(test_code)
    x_train_char = char_vectorizer.fit_transform(train_code)
    x_test_char = char_vectorizer.transform(test_code)

    x_train = hstack([x_train_word, x_train_char], format="csr", dtype=np.float32)
    x_test = hstack([x_test_word, x_test_char], format="csr", dtype=np.float32)

    metadata = {
        "word_features": int(len(word_vectorizer.get_feature_names_out())),
        "char_features": int(len(char_vectorizer.get_feature_names_out())),
        "total_features": int(x_train.shape[1]),
    }

    del x_train_word, x_test_word, x_train_char, x_test_char
    gc.collect()

    return x_train, x_test, word_vectorizer, char_vectorizer, metadata


def _top_feature_rows(
    model: SGDClassifier,
    word_vectorizer: TfidfVectorizer,
    char_vectorizer: TfidfVectorizer,
    fold_id: int,
    top_n: int,
) -> pd.DataFrame:
    """Return the top positive/negative LR coefficients for model-level interpretation."""
    coefficients = np.asarray(model.coef_).reshape(-1)
    word_features = word_vectorizer.get_feature_names_out().astype(str)
    char_features = char_vectorizer.get_feature_names_out().astype(str)

    feature_names = np.concatenate(
        [np.char.add("word::", word_features), np.char.add("char::", char_features)]
    )
    feature_types = np.concatenate(
        [np.repeat("word", len(word_features)), np.repeat("char", len(char_features))]
    )

    if len(coefficients) != len(feature_names):
        raise RuntimeError(
            "Feature/coefficient mismatch: "
            f"{len(feature_names):,} features vs {len(coefficients):,} coefficients."
        )

    top_n = min(max(0, int(top_n)), len(coefficients))
    columns = ["fold", "direction", "rank", "feature_type", "feature", "coefficient", "abs_coefficient"]
    if top_n == 0:
        return pd.DataFrame(columns=columns)

    positive_indices = np.argsort(coefficients)[-top_n:][::-1]
    negative_indices = np.argsort(coefficients)[:top_n]

    rows: list[dict] = []
    for direction, indices in (
        ("vulnerable_associated", positive_indices),
        ("non_vulnerable_associated", negative_indices),
    ):
        for rank, index in enumerate(indices, start=1):
            rows.append(
                {
                    "fold": int(fold_id),
                    "direction": direction,
                    "rank": int(rank),
                    "feature_type": str(feature_types[index]),
                    "feature": str(feature_names[index]),
                    "coefficient": float(coefficients[index]),
                    "abs_coefficient": float(abs(coefficients[index])),
                }
            )
    return pd.DataFrame(rows, columns=columns)


def _assert_project_disjoint(train_frame: pd.DataFrame, test_frame: pd.DataFrame, project_column: str, context: str) -> None:
    """Independently verify no project appears on both sides of a split."""
    overlap = set(train_frame[project_column]).intersection(set(test_frame[project_column]))
    if overlap:
        raise RuntimeError(f"Project leakage in {context}. Examples: {sorted(overlap)[:10]}")


def _assert_two_classes(frame: pd.DataFrame, label_column: str, context: str) -> None:
    """Fail loudly if a split lost one of the two classes."""
    values = set(frame[label_column].astype(int).unique().tolist())
    if values != {0, 1}:
        raise RuntimeError(f"{context} must contain both classes; observed {sorted(values)}.")


def _run_inner_search(
    outer_train_frame: pd.DataFrame,
    outer_fold_id: int,
    config: Exp1Config,
) -> tuple[pd.DataFrame, dict]:
    """Select TF-IDF capacity, alpha, and threshold via pooled inner-CV PR-AUC on this fold's training projects only."""
    outer_label = f"Outer fold {outer_fold_id + 1}/{config.n_splits}"
    combos = _vectorizer_grid(config)
    _log(
        f"{outer_label} | inner search started ({config.inner_n_splits}-fold project-grouped CV; "
        f"{len(combos)} TF-IDF combos x {len(config.sgd_alpha_grid)} alpha values).",
        config.verbose,
    )

    splitter = StratifiedGroupKFold(
        n_splits=config.inner_n_splits,
        shuffle=True,
        random_state=config.inner_random_state + int(outer_fold_id),
    )
    dummy_x = np.zeros((len(outer_train_frame), 1), dtype=np.uint8)
    labels = outer_train_frame[config.label_column].to_numpy(dtype=np.int8)
    groups = outer_train_frame[config.project_column].to_numpy()

    predictions_by_combo: dict[tuple, list[pd.DataFrame]] = {
        (*combo, alpha): [] for combo in combos for alpha in config.sgd_alpha_grid
    }
    summary_rows: list[dict] = []

    for inner_fold_id, (inner_train_pos, inner_valid_pos) in enumerate(
        splitter.split(dummy_x, labels, groups)
    ):
        inner_train = outer_train_frame.iloc[inner_train_pos].reset_index(drop=True)
        inner_valid = outer_train_frame.iloc[inner_valid_pos].reset_index(drop=True)
        context = f"{outer_label}, inner fold {inner_fold_id + 1}/{config.inner_n_splits}"
        _assert_project_disjoint(inner_train, inner_valid, config.project_column, context)
        _assert_two_classes(inner_valid, config.label_column, f"{context} validation")

        y_train = inner_train[config.label_column].to_numpy(dtype=np.int8)
        y_valid = inner_valid[config.label_column].to_numpy(dtype=np.int8)

        for word_max_features, char_max_features, word_min_df, char_min_df in combos:
            x_train, x_valid, _, _, _ = _fit_and_transform(
                train_code=inner_train[config.code_column],
                test_code=inner_valid[config.code_column],
                config=config,
                word_max_features=word_max_features,
                char_max_features=char_max_features,
                word_min_df=word_min_df,
                char_min_df=char_min_df,
            )

            for alpha in config.sgd_alpha_grid:
                model = _build_model(config, alpha)
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore", ConvergenceWarning)
                    model.fit(x_train, y_train)
                positive_index = np.where(model.classes_ == 1)[0][0]
                y_score = model.predict_proba(x_valid)[:, positive_index]

                key = (word_max_features, char_max_features, word_min_df, char_min_df, alpha)
                combo_predictions = inner_valid[[config.source_id_column, config.label_column]].copy()
                combo_predictions = combo_predictions.rename(
                    columns={config.source_id_column: "source_row_id", config.label_column: "label"}
                )
                combo_predictions["y_score"] = y_score.astype(np.float64)
                predictions_by_combo[key].append(combo_predictions)

            del x_train, x_valid
            gc.collect()

        _log(f"{context} | done.", config.verbose)
        del inner_train, inner_valid
        gc.collect()

    for word_max_features, char_max_features, word_min_df, char_min_df in combos:
        for alpha in config.sgd_alpha_grid:
            key = (word_max_features, char_max_features, word_min_df, char_min_df, alpha)
            pooled = pd.concat(predictions_by_combo[key], ignore_index=True)
            pooled_pr_auc = float(average_precision_score(pooled["label"], pooled["y_score"]))
            summary_rows.append(
                {
                    "outer_fold": int(outer_fold_id),
                    "word_max_features": int(word_max_features),
                    "char_max_features": int(char_max_features),
                    "word_min_df": int(word_min_df),
                    "char_min_df": int(char_min_df),
                    "sgd_alpha": float(alpha),
                    "inner_pooled_pr_auc": pooled_pr_auc,
                    "inner_oof_rows": int(len(pooled)),
                }
            )

    summary_df = pd.DataFrame(summary_rows)
    ordered = summary_df.sort_values(
        ["inner_pooled_pr_auc", "word_max_features", "sgd_alpha"],
        ascending=[False, True, False],
        kind="stable",
    ).reset_index(drop=True)
    best = ordered.iloc[0]
    best_key = (
        int(best["word_max_features"]),
        int(best["char_max_features"]),
        int(best["word_min_df"]),
        int(best["char_min_df"]),
        float(best["sgd_alpha"]),
    )
    best_pooled_predictions = pd.concat(predictions_by_combo[best_key], ignore_index=True)
    selected_threshold, threshold_metrics = select_f1_threshold(
        labels=best_pooled_predictions["label"], scores=best_pooled_predictions["y_score"]
    )

    selection = {
        "outer_fold": int(outer_fold_id),
        "word_max_features": best_key[0],
        "char_max_features": best_key[1],
        "word_min_df": best_key[2],
        "char_min_df": best_key[3],
        "sgd_alpha": best_key[4],
        "decision_threshold": selected_threshold,
        "inner_pooled_pr_auc": float(best["inner_pooled_pr_auc"]),
        "inner_validation_f1": float(threshold_metrics["f1"]),
    }
    _log(
        f"{outer_label} | selected word_max_features={best_key[0]}, char_max_features={best_key[1]}, "
        f"word_min_df={best_key[2]}, char_min_df={best_key[3]}, alpha={best_key[4]:g}, "
        f"threshold={selected_threshold:.2f} (inner PR-AUC={best['inner_pooled_pr_auc']:.4f}).",
        config.verbose,
    )

    return summary_df, selection


def _fit_outer_fold(
    outer_train_frame: pd.DataFrame,
    outer_test_frame: pd.DataFrame,
    outer_fold_id: int,
    selection: dict,
    config: Exp1Config,
) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    """Refit the inner-selected configuration on the full outer-train fold and score the outer-test fold once."""
    outer_label = f"Outer fold {outer_fold_id + 1}/{config.n_splits}"
    fold_start = time.perf_counter()

    x_train, x_test, word_vectorizer, char_vectorizer, vector_metadata = _fit_and_transform(
        train_code=outer_train_frame[config.code_column],
        test_code=outer_test_frame[config.code_column],
        config=config,
        word_max_features=selection["word_max_features"],
        char_max_features=selection["char_max_features"],
        word_min_df=selection["word_min_df"],
        char_min_df=selection["char_min_df"],
    )

    y_train = outer_train_frame[config.label_column].to_numpy(dtype=np.int8)
    model = _build_model(config, selection["sgd_alpha"])

    fit_start = time.perf_counter()
    with warnings.catch_warnings(record=True) as caught_warnings:
        warnings.simplefilter("always", ConvergenceWarning)
        model.fit(x_train, y_train)
    fit_seconds = float(time.perf_counter() - fit_start)
    convergence_count = sum(1 for w in caught_warnings if issubclass(w.category, ConvergenceWarning))

    positive_index = np.where(model.classes_ == 1)[0][0]
    y_score = model.predict_proba(x_test)[:, positive_index]

    prediction_frame = outer_test_frame[
        [config.source_id_column, config.fold_column, config.label_column, config.project_column]
    ].copy()
    prediction_frame = prediction_frame.rename(
        columns={
            config.source_id_column: "source_row_id",
            config.fold_column: "fold",
            config.label_column: "label",
            config.project_column: "project",
        }
    )
    prediction_frame["y_score"] = y_score.astype(np.float64)

    top_features = _top_feature_rows(
        model=model,
        word_vectorizer=word_vectorizer,
        char_vectorizer=char_vectorizer,
        fold_id=outer_fold_id,
        top_n=config.top_features_per_direction,
    )

    total_seconds = float(time.perf_counter() - fold_start)
    training_metadata = {
        "fold": int(outer_fold_id),
        "train_rows": int(len(outer_train_frame)),
        "test_rows": int(len(outer_test_frame)),
        "train_positive_rate": float(outer_train_frame[config.label_column].mean()),
        "test_positive_rate": float(outer_test_frame[config.label_column].mean()),
        "train_unique_projects": int(outer_train_frame[config.project_column].nunique()),
        "test_unique_projects": int(outer_test_frame[config.project_column].nunique()),
        **selection,
        **vector_metadata,
        "model_fit_seconds": fit_seconds,
        "total_fold_seconds": total_seconds,
        "convergence_warning_count": int(convergence_count),
    }

    _log(f"{outer_label} | fit+scored in {_format_seconds(total_seconds)}.", config.verbose)

    del x_train, x_test, word_vectorizer, char_vectorizer, model
    gc.collect()

    return prediction_frame, top_features, training_metadata


def _validate_fold_project_separation(frame: pd.DataFrame, config: Exp1Config) -> None:
    """Independently verify the no-project-leakage property for every outer fold."""
    for fold_id in range(config.n_splits):
        test_projects = set(frame.loc[frame[config.fold_column] == fold_id, config.project_column])
        train_projects = set(frame.loc[frame[config.fold_column] != fold_id, config.project_column])
        overlap = test_projects.intersection(train_projects)
        if overlap:
            raise ValueError(f"Project leakage detected in fold {fold_id}. Examples: {sorted(overlap)[:10]}")


def _prepare_dataset_with_folds(
    normalized_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    config: Exp1Config,
) -> pd.DataFrame:
    """Attach the immutable manifest and validate all EXP-1 inputs."""
    split_config = SplitConfig(n_splits=config.n_splits, random_state=config.random_state, shuffle=True)
    assert_manifest_integrity(manifest, config=split_config)

    merged = apply_manifest(frame=normalized_frame, manifest=manifest, source_id_column=config.source_id_column)
    merged = _validate_experiment_frame(merged, config)
    _validate_fold_project_separation(merged, config)
    return merged


def run_exp1_profile_fold(
    normalized_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    fold_id: int = 0,
    config: Exp1Config = Exp1Config(),
) -> dict:
    """Run the inner search plus refit for exactly ONE outer fold, to check feasibility before the full 5-fold run."""
    _validate_config(config)
    if fold_id not in range(config.n_splits):
        raise ValueError(f"fold_id must be in [0, {config.n_splits - 1}], received {fold_id}.")

    _log(f"CS1-EXP1 profiling mode: running outer fold {fold_id + 1}/{config.n_splits} only.", config.verbose)

    dataset_with_folds = _prepare_dataset_with_folds(normalized_frame, manifest, config)
    train_frame = dataset_with_folds.loc[dataset_with_folds[config.fold_column] != fold_id].reset_index(drop=True)
    test_frame = dataset_with_folds.loc[dataset_with_folds[config.fold_column] == fold_id].reset_index(drop=True)

    inner_summary, selection = _run_inner_search(train_frame, fold_id, config)
    predictions, top_features, training_metadata = _fit_outer_fold(train_frame, test_frame, fold_id, selection, config)

    profile_metrics = compute_binary_metrics(
        labels=predictions["label"], scores=predictions["y_score"], threshold=selection["decision_threshold"]
    )

    del train_frame, test_frame, dataset_with_folds
    gc.collect()

    return {
        "fold_id": int(fold_id),
        "predictions": predictions,
        "top_features": top_features,
        "inner_search": inner_summary,
        "selection": selection,
        "training_metadata": pd.DataFrame([training_metadata]),
        "profile_metrics": profile_metrics,
    }


def _safe_experiment_name(name: str) -> str:
    """Filesystem-safe slug for artifact filenames."""
    lowered = name.strip().lower().replace(" ", "_")
    return "".join(char if char.isalnum() or char in {"_", "-"} else "_" for char in lowered)


def _save_exp1_artifacts(
    results: Mapping[str, object],
    output_dir: Path | str,
    config: Exp1Config,
    additional_metadata: Optional[Mapping[str, object]] = None,
) -> Exp1Artifacts:
    """Save complete EXP-1 artifacts plus shared evaluation outputs."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    oof_predictions = results["oof_predictions"]
    fold_training = results["fold_training"]
    inner_search = results["inner_search"]
    top_features = results["top_features"]
    evaluation = results["evaluation"]

    safe_name = _safe_experiment_name(config.experiment_name)
    config_json = output_dir / f"{safe_name}_config.json"
    fold_training_csv = output_dir / f"{safe_name}_fold_training.csv"
    inner_search_csv = output_dir / f"{safe_name}_inner_search.csv"
    top_features_csv = output_dir / f"{safe_name}_top_features.csv"
    run_metadata_json = output_dir / f"{safe_name}_run_metadata.json"

    with config_json.open("w", encoding="utf-8") as file:
        json.dump({"exp1_version": EXP1_VERSION, "config": asdict(config)}, file, indent=2)

    fold_training.to_csv(fold_training_csv, index=False)
    inner_search.to_csv(inner_search_csv, index=False)
    top_features.to_csv(top_features_csv, index=False)

    evaluation_paths = save_evaluation_artifacts(
        evaluation=evaluation,
        output_dir=output_dir,
        experiment_name=config.experiment_name,
        config=EvaluationConfig(threshold=float(fold_training["decision_threshold"].mean()), expected_n_folds=config.n_splits),
        additional_metadata={
            "exp1_version": EXP1_VERSION,
            "model": "class-weighted L2 Logistic Regression optimized with SGDClassifier(loss=log_loss)",
            "feature_representation": "word TF-IDF + character TF-IDF, capacity and alpha selected per outer fold via inner CV",
            "score_interpretation": "Class-weighted SGD Logistic Regression risk score; not a calibrated real-world probability.",
            **dict(additional_metadata or {}),
        },
    )

    run_metadata = {
        "exp1_version": EXP1_VERSION,
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "experiment_name": config.experiment_name,
        "config": asdict(config),
        "n_oof_predictions": int(len(oof_predictions)),
        "folds_completed": sorted(oof_predictions["fold"].unique().astype(int).tolist()),
        "selected_hyperparameters_by_fold": fold_training[
            ["fold", "word_max_features", "char_max_features", "word_min_df", "char_min_df", "sgd_alpha", "decision_threshold"]
        ].to_dict(orient="records"),
        "additional_metadata": dict(additional_metadata or {}),
    }
    with run_metadata_json.open("w", encoding="utf-8") as file:
        json.dump(run_metadata, file, indent=2, default=str)

    return Exp1Artifacts(
        config_json=config_json,
        fold_training_csv=fold_training_csv,
        inner_search_csv=inner_search_csv,
        top_features_csv=top_features_csv,
        run_metadata_json=run_metadata_json,
        evaluation_paths=evaluation_paths,
    )


def run_exp1(
    normalized_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    config: Exp1Config = Exp1Config(),
    output_dir: Optional[Path | str] = None,
    additional_metadata: Optional[Mapping[str, object]] = None,
) -> dict:
    """Run the official rotating 5-fold CS1-EXP1-LR experiment, with a full inner-CV search per outer fold."""
    _validate_config(config)
    _log(f"CS1-EXP1 official run started: {config.n_splits} rotating outer folds.", config.verbose)

    dataset_with_folds = _prepare_dataset_with_folds(normalized_frame, manifest, config)

    all_predictions: list[pd.DataFrame] = []
    all_top_features: list[pd.DataFrame] = []
    all_inner_search: list[pd.DataFrame] = []
    training_rows: list[dict] = []

    run_start = time.perf_counter()

    for fold_id in range(config.n_splits):
        train_frame = dataset_with_folds.loc[dataset_with_folds[config.fold_column] != fold_id].reset_index(drop=True)
        test_frame = dataset_with_folds.loc[dataset_with_folds[config.fold_column] == fold_id].reset_index(drop=True)

        if train_frame.empty or test_frame.empty:
            raise RuntimeError(f"Fold {fold_id} has an empty train/test partition.")
        _assert_two_classes(test_frame, config.label_column, f"fold {fold_id} test")

        inner_summary, selection = _run_inner_search(train_frame, fold_id, config)
        fold_predictions, fold_features, fold_metadata = _fit_outer_fold(
            train_frame, test_frame, fold_id, selection, config
        )

        all_predictions.append(fold_predictions)
        all_top_features.append(fold_features)
        all_inner_search.append(inner_summary)
        training_rows.append(fold_metadata)

        del train_frame, test_frame
        gc.collect()

    oof_predictions = pd.concat(all_predictions, ignore_index=True).sort_values("source_row_id", kind="stable").reset_index(drop=True)
    fold_training = pd.DataFrame(training_rows).sort_values("fold").reset_index(drop=True)
    inner_search = pd.concat(all_inner_search, ignore_index=True).sort_values(
        ["outer_fold", "inner_pooled_pr_auc"], ascending=[True, False]
    ).reset_index(drop=True)
    top_features = pd.concat(all_top_features, ignore_index=True).sort_values(["fold", "direction", "rank"]).reset_index(drop=True)

    if len(oof_predictions) != len(dataset_with_folds):
        raise RuntimeError(
            f"OOF prediction count does not match dataset size: {len(oof_predictions):,} vs {len(dataset_with_folds):,}."
        )
    if oof_predictions["source_row_id"].duplicated().any():
        raise RuntimeError("Duplicate source_row_id found in OOF predictions.")

    mean_threshold = float(fold_training["decision_threshold"].mean())
    evaluation = evaluate_oof_predictions(
        oof_predictions, config=EvaluationConfig(threshold=mean_threshold, expected_n_folds=config.n_splits)
    )

    total_runtime_seconds = float(time.perf_counter() - run_start)
    _log(f"CS1-EXP1 official run completed in {_format_seconds(total_runtime_seconds)}.", config.verbose)

    results = {
        "oof_predictions": evaluation["predictions"],
        "fold_training": fold_training,
        "inner_search": inner_search,
        "top_features": top_features,
        "evaluation": evaluation,
        "total_runtime_seconds": total_runtime_seconds,
    }

    if output_dir is not None:
        results["artifacts"] = _save_exp1_artifacts(results, output_dir, config, additional_metadata)
        _log(f"Artifacts saved to: {Path(output_dir)}", config.verbose)

    return results


__all__ = [
    "EXP1_VERSION",
    "Exp1Artifacts",
    "Exp1Config",
    "run_exp1",
    "run_exp1_profile_fold",
]
