"""
CS1-EXP2-MLP: train-only TF-IDF + TruncatedSVD + static features + shallow MLP.

    normalized C/C++ function text
        -> word + character TF-IDF -> TruncatedSVD (dense)
        -> concat with 54 deterministic static features
        -> StandardScaler
        -> shallow MLP (hidden_dim_1 -> hidden_dim_2 -> 1 logit)

Evaluation protocol
--------------------
5-fold project-grouped, stratified CV; every fold takes a turn as the test
set (no separate fixed holdout). For each outer fold, hyperparameters are
selected via 3-fold inner CV on that outer fold's training projects only,
in two stages to keep the search tractable (a full joint grid would need
thousands of TruncatedSVD refits):

  Stage A (representation): word/char TF-IDF capacity (max_features, min_df)
  and svd_n_components, with the MLP architecture held at its default.
  Stage B (architecture): hidden_dim_1, hidden_dim_2, learning_rate, reusing
  Stage A's winning TF-IDF+SVD representation (already computed per inner
  fold, so Stage B needs no further vectorizer/SVD refitting).

The decision threshold is then selected (F1-maximizing grid) from the
winning configuration's pooled inner-validation scores. The winning
configuration is refit on the full outer-training partition (using one
project-disjoint split for early stopping) and scored once on the outer
test fold. Reported metrics are mean +/- std across the 5 outer folds.
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import gc
import itertools
import json
from pathlib import Path
import random
import time
from typing import Mapping, Optional, Sequence

import numpy as np
import pandas as pd
from scipy.sparse import hstack
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.preprocessing import StandardScaler

try:
    import torch
    from torch import Tensor, nn
    from torch.utils.data import DataLoader, TensorDataset
except ImportError as exc:  # pragma: no cover - environment guard
    raise ImportError(
        "CS1-EXP2-MLP requires PyTorch. Install a compatible torch build before importing this module."
    ) from exc

from utils.evaluation import (
    EvaluationConfig,
    compute_binary_metrics,
    evaluate_oof_predictions,
    save_evaluation_artifacts,
    select_f1_threshold,
)
from utils.split_manifest import SplitConfig, apply_manifest, assert_manifest_integrity
from ..static_features import FEATURE_COLUMNS


EXP2_VERSION = "cs1-exp2-svd-static-mlp-v2-nested-rotating-5fold"


@dataclass(frozen=True)
class Exp2Config:
    """Declared reproducible configuration for CS1-EXP2-MLP, including every searched grid."""

    experiment_name: str = "cs1_exp2_mlp"
    code_column: str = "normalized_code"
    source_id_column: str = "source_row_id"
    label_column: str = "label"
    project_column: str = "project"
    fold_column: str = "fold"

    n_splits: int = 5
    random_state: int = 42

    # Same lexical representation grid as EXP-1.
    word_ngram_range: tuple[int, int] = (1, 3)
    word_max_df: float = 0.995
    word_max_features_grid: tuple[int, ...] = (20_000, 50_000, 80_000)
    word_min_df_grid: tuple[int, ...] = (2, 3)

    char_analyzer: str = "char"
    char_ngram_range: tuple[int, int] = (3, 4)
    char_max_df: float = 0.995
    char_max_features_grid: tuple[int, ...] = (30_000, 60_000, 90_000)
    char_min_df_grid: tuple[int, ...] = (5, 8)

    lowercase: bool = False
    sublinear_tf: bool = True
    tfidf_norm: str = "l2"

    # TruncatedSVD is fitted only on inner-fold training data.
    svd_algorithm: str = "randomized"
    svd_n_iter: int = 5
    svd_n_oversamples: int = 10
    svd_n_components_grid: tuple[int, ...] = (128, 256, 384)

    # Stage B architecture search.
    hidden_dim_1_grid: tuple[int, ...] = (64, 128, 256)
    hidden_dim_2_grid: tuple[int, ...] = (32, 64, 128)
    learning_rate_grid: tuple[float, ...] = (1e-3, 5e-4, 1e-4)

    # Fixed default architecture used while Stage A searches representation.
    default_hidden_dim_1: int = 128
    default_hidden_dim_2: int = 64
    default_learning_rate: float = 1e-3

    max_epochs: int = 15
    early_stopping_patience: int = 3
    early_stopping_min_delta: float = 1e-4
    batch_size_gpu: int = 2_048
    batch_size_cpu: int = 1_024
    weight_decay: float = 1e-4
    use_pos_weight: bool = True

    inner_n_splits: int = 3
    inner_random_state: int = 20260707
    selection_metric: str = "average_precision_pr_auc"

    device: str = "auto"
    dataloader_num_workers: int = 0
    verbose: bool = True


@dataclass(frozen=True)
class Exp2Artifacts:
    """Artifacts generated by a complete official EXP-2 run."""

    config_json: Path
    fold_training_csv: Path
    inner_search_csv: Path
    training_history_csv: Path
    run_metadata_json: Path
    evaluation_paths: object


class ShallowMLP(nn.Module):
    """Feed-forward binary classifier returning logits."""

    def __init__(self, input_dim: int, hidden_dim_1: int, hidden_dim_2: int):
        """Build the hidden_dim_1 -> hidden_dim_2 -> 1 feed-forward network."""
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, hidden_dim_1),
            nn.ReLU(),
            nn.Linear(hidden_dim_1, hidden_dim_2),
            nn.ReLU(),
            nn.Linear(hidden_dim_2, 1),
        )

    def forward(self, features: Tensor) -> Tensor:
        """Return logits for a batch of dense features."""
        return self.network(features).squeeze(dim=1)


def _log(message: str, enabled: bool = True) -> None:
    """Print an immediate timestamped progress message when verbose mode is enabled."""
    if enabled:
        timestamp = datetime.now().strftime("%H:%M:%S")
        print(f"[{timestamp}] {message}", flush=True)


def _format_seconds(seconds: float) -> str:
    """Human-readable elapsed time."""
    seconds = float(seconds)
    return f"{seconds:.1f}s" if seconds < 60 else f"{seconds / 60:.2f} min"


def _require_columns(frame: pd.DataFrame, columns: Sequence[str]) -> None:
    """Raise a clear error listing any missing required column."""
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        raise KeyError(
            f"Missing required column(s): {missing}. Available columns: {sorted(frame.columns.tolist())}"
        )


def _validate_config(config: Exp2Config) -> None:
    """Fail fast on an invalid configuration before any fold work starts."""
    if config.n_splits < 2:
        raise ValueError("n_splits must be >= 2.")
    if config.inner_n_splits < 2:
        raise ValueError("inner_n_splits must be >= 2.")
    for name, grid in (
        ("word_max_features_grid", config.word_max_features_grid),
        ("char_max_features_grid", config.char_max_features_grid),
        ("word_min_df_grid", config.word_min_df_grid),
        ("char_min_df_grid", config.char_min_df_grid),
        ("svd_n_components_grid", config.svd_n_components_grid),
        ("hidden_dim_1_grid", config.hidden_dim_1_grid),
        ("hidden_dim_2_grid", config.hidden_dim_2_grid),
        ("learning_rate_grid", config.learning_rate_grid),
    ):
        if not grid or any(v <= 0 for v in grid):
            raise ValueError(f"{name} must be non-empty with positive values.")
    if config.max_epochs < 1:
        raise ValueError("max_epochs must be >= 1.")
    if config.early_stopping_patience < 1:
        raise ValueError("early_stopping_patience must be >= 1.")
    if config.batch_size_gpu < 1 or config.batch_size_cpu < 1:
        raise ValueError("Batch sizes must be >= 1.")
    if config.weight_decay < 0.0:
        raise ValueError("weight_decay must be >= 0.")
    if config.device not in {"auto", "cpu", "cuda"}:
        raise ValueError("device must be one of: 'auto', 'cpu', 'cuda'.")
    if config.dataloader_num_workers < 0:
        raise ValueError("dataloader_num_workers must be >= 0.")
    if config.selection_metric != "average_precision_pr_auc":
        raise ValueError("This implementation selects every grid by pooled inner PR-AUC.")


def _validate_dataset_with_folds(frame: pd.DataFrame, config: Exp2Config) -> pd.DataFrame:
    """Validate the normalized data after its fixed fold assignment is attached."""
    _require_columns(
        frame,
        [config.source_id_column, config.code_column, config.label_column, config.project_column, config.fold_column],
    )
    checked = frame.copy()
    if checked[config.source_id_column].isna().any():
        raise ValueError("source_row_id contains missing values.")
    if checked[config.source_id_column].duplicated().any():
        raise ValueError("source_row_id contains duplicate values.")

    checked[config.code_column] = checked[config.code_column].fillna("").astype(str)
    if checked[config.code_column].str.strip().eq("").any():
        raise ValueError("EXP-2 received empty code rows. Use a dataset that passed the quality gate.")

    labels = pd.to_numeric(checked[config.label_column], errors="raise")
    if not labels.isin([0, 1]).all():
        raise ValueError("label must contain only 0 and 1.")
    checked[config.label_column] = labels.astype("int8")

    checked[config.project_column] = checked[config.project_column].fillna("").astype(str).str.strip()
    if checked[config.project_column].eq("").any():
        raise ValueError("project contains missing or empty identifiers.")

    folds = pd.to_numeric(checked[config.fold_column], errors="raise").astype(int)
    expected = set(range(config.n_splits))
    observed = set(folds.unique().tolist())
    if observed != expected:
        raise ValueError(f"Expected folds {sorted(expected)}; observed {sorted(observed)}.")
    checked[config.fold_column] = folds.astype("int8")
    return checked


def _validate_static_feature_frame(static_features_frame: pd.DataFrame, config: Exp2Config) -> pd.DataFrame:
    """Validate the static-feature cache and index it by source_row_id."""
    required = [config.source_id_column, *FEATURE_COLUMNS]
    _require_columns(static_features_frame, required)

    static_checked = static_features_frame[required].copy()
    if static_checked[config.source_id_column].isna().any():
        raise ValueError("Static feature cache has missing source_row_id values.")
    if static_checked[config.source_id_column].duplicated().any():
        raise ValueError("Static feature cache has duplicate source_row_id values.")

    for column in FEATURE_COLUMNS:
        static_checked[column] = pd.to_numeric(static_checked[column], errors="raise").astype(np.float32)

    values = static_checked[FEATURE_COLUMNS].to_numpy(dtype=np.float32)
    if not np.isfinite(values).all():
        raise ValueError("Static feature cache contains NaN or infinite values.")
    if (values < 0).any():
        raise ValueError("Static feature cache contains negative proxy values.")

    return static_checked.set_index(config.source_id_column, drop=True)


def _prepare_dataset_and_static_lookup(
    normalized_frame: pd.DataFrame,
    static_features_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    config: Exp2Config,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Attach the shared fold manifest and validate static-cache alignment."""
    split_config = SplitConfig(n_splits=config.n_splits, random_state=config.random_state)
    assert_manifest_integrity(manifest, config=split_config)

    dataset = apply_manifest(normalized_frame, manifest, source_id_column=config.source_id_column)
    dataset = _validate_dataset_with_folds(dataset, config)
    static_lookup = _validate_static_feature_frame(static_features_frame, config)

    missing_static = pd.Index(dataset[config.source_id_column]).difference(static_lookup.index)
    if len(missing_static):
        raise ValueError(f"Static feature cache is missing {len(missing_static):,} required IDs.")

    for fold_id in range(config.n_splits):
        test_projects = set(dataset.loc[dataset[config.fold_column] == fold_id, config.project_column])
        train_projects = set(dataset.loc[dataset[config.fold_column] != fold_id, config.project_column])
        overlap = test_projects.intersection(train_projects)
        if overlap:
            raise RuntimeError(f"Project leakage detected in fold {fold_id}; examples: {sorted(overlap)[:10]}")

    return dataset, static_lookup


def _build_word_vectorizer(config: Exp2Config, max_features: int, min_df: int) -> TfidfVectorizer:
    """Word TF-IDF with a custom token pattern that retains one-character tokens."""
    return TfidfVectorizer(
        analyzer="word",
        token_pattern=r"(?u)\b\w+\b",
        ngram_range=config.word_ngram_range,
        min_df=min_df,
        max_df=config.word_max_df,
        max_features=max_features,
        lowercase=config.lowercase,
        sublinear_tf=config.sublinear_tf,
        norm=config.tfidf_norm,
        dtype=np.float32,
    )


def _build_char_vectorizer(config: Exp2Config, max_features: int, min_df: int) -> TfidfVectorizer:
    """Character TF-IDF over raw source text."""
    return TfidfVectorizer(
        analyzer=config.char_analyzer,
        ngram_range=config.char_ngram_range,
        min_df=min_df,
        max_df=config.char_max_df,
        max_features=max_features,
        lowercase=config.lowercase,
        sublinear_tf=config.sublinear_tf,
        norm=config.tfidf_norm,
        dtype=np.float32,
    )


def _fit_lexical_matrices(
    fit_code: pd.Series,
    test_code: pd.Series,
    config: Exp2Config,
    word_max_features: int,
    char_max_features: int,
    word_min_df: int,
    char_min_df: int,
):
    """Fit train-only word/char TF-IDF for one combo and transform the matching test code."""
    word_vectorizer = _build_word_vectorizer(config, word_max_features, word_min_df)
    char_vectorizer = _build_char_vectorizer(config, char_max_features, char_min_df)

    x_fit_word = word_vectorizer.fit_transform(fit_code)
    x_test_word = word_vectorizer.transform(test_code)
    x_fit_char = char_vectorizer.fit_transform(fit_code)
    x_test_char = char_vectorizer.transform(test_code)

    x_fit_lexical = hstack([x_fit_word, x_fit_char], format="csr", dtype=np.float32)
    x_test_lexical = hstack([x_test_word, x_test_char], format="csr", dtype=np.float32)

    metadata = {
        "word_features": int(x_fit_word.shape[1]),
        "char_features": int(x_fit_char.shape[1]),
        "lexical_features": int(x_fit_lexical.shape[1]),
    }
    del x_fit_word, x_test_word, x_fit_char, x_test_char
    gc.collect()
    return x_fit_lexical, x_test_lexical, metadata


def _fit_and_transform_svd(x_fit_lexical, x_test_lexical, config: Exp2Config, svd_n_components: int, seed: int):
    """Fit TruncatedSVD only on inner-fit sparse lexical features."""
    if svd_n_components >= x_fit_lexical.shape[1]:
        raise ValueError(
            f"svd_n_components ({svd_n_components}) must be lower than the lexical feature count "
            f"({x_fit_lexical.shape[1]})."
        )
    svd = TruncatedSVD(
        n_components=svd_n_components,
        algorithm=config.svd_algorithm,
        n_iter=config.svd_n_iter,
        n_oversamples=config.svd_n_oversamples,
        random_state=seed,
    )
    x_fit_svd = np.asarray(svd.fit_transform(x_fit_lexical), dtype=np.float32)
    x_test_svd = np.asarray(svd.transform(x_test_lexical), dtype=np.float32)
    explained_variance = float(np.sum(svd.explained_variance_ratio_))
    return x_fit_svd, x_test_svd, explained_variance


def _get_static_matrix(static_lookup: pd.DataFrame, source_ids: pd.Series) -> np.ndarray:
    """Fetch static features in exactly the requested source-ID order."""
    matrix = static_lookup.loc[pd.Index(source_ids), FEATURE_COLUMNS].to_numpy(dtype=np.float32, copy=True)
    if not np.isfinite(matrix).all():
        raise RuntimeError("Static feature matrix contains NaN or infinite values.")
    return matrix


def _fit_scaler_and_transform(x_fit: np.ndarray, *others: np.ndarray):
    """Fit StandardScaler on x_fit only, then transform x_fit and every array in others."""
    scaler = StandardScaler(copy=True, with_mean=True, with_std=True)
    x_fit_scaled = scaler.fit_transform(x_fit).astype(np.float32, copy=False)
    others_scaled = tuple(scaler.transform(x).astype(np.float32, copy=False) for x in others)
    for matrix in (x_fit_scaled, *others_scaled):
        if not np.isfinite(matrix).all():
            raise RuntimeError("Scaled feature matrix contains NaN/inf.")
    return (x_fit_scaled, *others_scaled)


def _resolve_device(config: Exp2Config) -> torch.device:
    """Pick CUDA when requested/available, otherwise CPU."""
    if config.device == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("device='cuda' was requested but PyTorch cannot access a CUDA GPU.")
        return torch.device("cuda")
    if config.device == "cpu":
        return torch.device("cpu")
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def _set_reproducible_seed(seed: int) -> None:
    """Seed every RNG this module touches."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def _build_loader(
    features: np.ndarray,
    labels: Optional[np.ndarray],
    batch_size: int,
    shuffle: bool,
    seed: int,
    device: torch.device,
    config: Exp2Config,
) -> DataLoader:
    """Wrap dense features (and optional labels) into a DataLoader."""
    feature_tensor = torch.from_numpy(np.asarray(features, dtype=np.float32))
    dataset = (
        TensorDataset(feature_tensor)
        if labels is None
        else TensorDataset(feature_tensor, torch.from_numpy(np.asarray(labels, dtype=np.float32)))
    )
    generator = torch.Generator()
    generator.manual_seed(seed)
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        generator=generator if shuffle else None,
        num_workers=config.dataloader_num_workers,
        pin_memory=(device.type == "cuda"),
        drop_last=False,
    )


def _predict_scores(model: ShallowMLP, features: np.ndarray, device: torch.device, batch_size: int, config: Exp2Config) -> np.ndarray:
    """Run the model over features with no gradient and return sigmoid scores."""
    loader = _build_loader(features, None, batch_size, False, config.random_state, device, config)
    model.eval()
    probabilities: list[np.ndarray] = []
    with torch.no_grad():
        for (batch_features,) in loader:
            batch_features = batch_features.to(device, non_blocking=True)
            probabilities.append(torch.sigmoid(model(batch_features)).detach().cpu().numpy().astype(np.float64))
    scores = np.concatenate(probabilities, axis=0)
    if not np.isfinite(scores).all() or (scores < 0.0).any() or (scores > 1.0).any():
        raise RuntimeError("MLP produced invalid probability scores.")
    return scores


def _train_mlp_with_early_stopping(
    x_fit: np.ndarray,
    y_fit: np.ndarray,
    x_validation: np.ndarray,
    y_validation: np.ndarray,
    config: Exp2Config,
    hidden_dim_1: int,
    hidden_dim_2: int,
    learning_rate: float,
    fold_seed: int,
    record_history: bool = False,
) -> tuple[ShallowMLP, dict, np.ndarray, torch.device]:
    """Train the MLP on fit rows and early-stop by validation PR-AUC; optionally record a per-epoch history."""
    _set_reproducible_seed(fold_seed)
    device = _resolve_device(config)
    if device.type == "cuda":
        torch.cuda.empty_cache()

    batch_size = config.batch_size_gpu if device.type == "cuda" else config.batch_size_cpu
    model = ShallowMLP(input_dim=int(x_fit.shape[1]), hidden_dim_1=hidden_dim_1, hidden_dim_2=hidden_dim_2).to(device)

    negatives, positives = int((y_fit == 0).sum()), int((y_fit == 1).sum())
    pos_weight_value = float(negatives / positives) if config.use_pos_weight else 1.0
    criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight_value, dtype=torch.float32, device=device))
    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=config.weight_decay)
    fit_loader = _build_loader(x_fit, y_fit, batch_size, True, fold_seed, device, config)

    best_state = deepcopy(model.state_dict())
    best_pr_auc, best_epoch, no_improve = float("-inf"), 0, 0
    history_rows: list[dict] = []

    for epoch in range(1, config.max_epochs + 1):
        model.train()
        train_loss_sum, train_row_count = 0.0, 0
        for batch_features, batch_labels in fit_loader:
            batch_features = batch_features.to(device, non_blocking=True)
            batch_labels = batch_labels.to(device, non_blocking=True)
            optimizer.zero_grad(set_to_none=True)
            logits = model(batch_features)
            loss = criterion(logits, batch_labels)
            loss.backward()
            optimizer.step()
            if record_history:
                rows = int(batch_labels.shape[0])
                train_loss_sum += float(loss.item()) * rows
                train_row_count += rows

        validation_scores = _predict_scores(model, x_validation, device, batch_size, config)
        validation_pr_auc = float(average_precision_score(y_validation, validation_scores))

        if record_history:
            validation_labels_t = torch.from_numpy(np.asarray(y_validation, dtype=np.float32))
            validation_scores_t = torch.from_numpy(np.asarray(validation_scores, dtype=np.float32)).clamp(1e-7, 1 - 1e-7)
            validation_loss = float(nn.functional.binary_cross_entropy(validation_scores_t, validation_labels_t).item())
            history_rows.append({
                "epoch": int(epoch),
                "train_weighted_bce_loss": float(train_loss_sum / train_row_count) if train_row_count else float("nan"),
                "validation_weighted_bce_loss": validation_loss,
                "validation_pr_auc": validation_pr_auc,
            })

        if validation_pr_auc > best_pr_auc + config.early_stopping_min_delta:
            best_pr_auc, best_epoch, no_improve = validation_pr_auc, epoch, 0
            best_state = deepcopy(model.state_dict())
        else:
            no_improve += 1
        if no_improve >= config.early_stopping_patience:
            break

    model.load_state_dict(best_state)
    best_validation_scores = _predict_scores(model, x_validation, device, batch_size, config)
    metadata = {
        "training_history": pd.DataFrame(history_rows),
        "device": str(device),
        "batch_size": int(batch_size),
        "positive_class_weight": float(pos_weight_value),
        "best_epoch": int(best_epoch),
        "best_validation_pr_auc": float(best_pr_auc),
    }
    return model, metadata, best_validation_scores, device


def _inner_splits(outer_train_frame: pd.DataFrame, config: Exp2Config, outer_fold_id: int) -> list[tuple[np.ndarray, np.ndarray]]:
    """Project-grouped, stratified 3-fold split of one outer fold's training partition."""
    splitter = StratifiedGroupKFold(
        n_splits=config.inner_n_splits, shuffle=True, random_state=config.inner_random_state + int(outer_fold_id)
    )
    dummy_x = np.zeros((len(outer_train_frame), 1), dtype=np.uint8)
    labels = outer_train_frame[config.label_column].to_numpy(dtype=np.int8)
    groups = outer_train_frame[config.project_column].to_numpy()
    return list(splitter.split(dummy_x, labels, groups))


def _build_combo_features(
    fit_frame: pd.DataFrame, valid_frame: pd.DataFrame, static_lookup: pd.DataFrame,
    config: Exp2Config, combo: tuple, outer_fold_id: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Build the scaled (SVD + static) feature matrices for one TF-IDF/SVD combo."""
    word_mf, char_mf, word_md, char_md, svd_components = combo
    x_fit_lex, x_valid_lex, _ = _fit_lexical_matrices(
        fit_frame[config.code_column], valid_frame[config.code_column], config, word_mf, char_mf, word_md, char_md
    )
    x_fit_svd, x_valid_svd, _ = _fit_and_transform_svd(
        x_fit_lex, x_valid_lex, config, svd_components, config.random_state + outer_fold_id
    )
    x_fit_static = _get_static_matrix(static_lookup, fit_frame[config.source_id_column])
    x_valid_static = _get_static_matrix(static_lookup, valid_frame[config.source_id_column])
    x_fit = np.hstack([x_fit_svd, x_fit_static]).astype(np.float32, copy=False)
    x_valid = np.hstack([x_valid_svd, x_valid_static]).astype(np.float32, copy=False)
    x_fit, x_valid = _fit_scaler_and_transform(x_fit, x_valid)
    y_fit = fit_frame[config.label_column].to_numpy(dtype=np.int8)
    y_valid = valid_frame[config.label_column].to_numpy(dtype=np.int8)
    return x_fit, y_fit, x_valid, y_valid, valid_frame[config.source_id_column].to_numpy()


def _stage_a_search(
    outer_train_frame: pd.DataFrame,
    static_lookup: pd.DataFrame,
    outer_fold_id: int,
    config: Exp2Config,
) -> tuple[pd.DataFrame, dict]:
    """Select TF-IDF capacity + svd_n_components by pooled inner PR-AUC, architecture held at default."""
    tfidf_combos = list(
        itertools.product(
            config.word_max_features_grid, config.char_max_features_grid, config.word_min_df_grid, config.char_min_df_grid
        )
    )
    combos = [(*t, s) for t in tfidf_combos for s in config.svd_n_components_grid]
    splits = _inner_splits(outer_train_frame, config, outer_fold_id)
    frames = [
        (outer_train_frame.iloc[fit_idx].reset_index(drop=True), outer_train_frame.iloc[valid_idx].reset_index(drop=True))
        for fit_idx, valid_idx in splits
    ]

    predictions_by_combo: dict[tuple, list[pd.DataFrame]] = {combo: [] for combo in combos}

    for inner_fold_id, (fit_frame, valid_frame) in enumerate(frames):
        for combo in combos:
            x_fit, y_fit, x_valid, y_valid, valid_ids = _build_combo_features(
                fit_frame, valid_frame, static_lookup, config, combo, outer_fold_id
            )
            _, _, valid_scores, _ = _train_mlp_with_early_stopping(
                x_fit, y_fit, x_valid, y_valid, config,
                config.default_hidden_dim_1, config.default_hidden_dim_2, config.default_learning_rate,
                fold_seed=config.random_state + 5_000 + outer_fold_id * 100 + inner_fold_id,
            )
            predictions_by_combo[combo].append(pd.DataFrame({"source_row_id": valid_ids, "label": y_valid, "y_score": valid_scores}))
            del x_fit, x_valid
        gc.collect()

    summary_rows = []
    for combo in combos:
        pooled = pd.concat(predictions_by_combo[combo], ignore_index=True)
        summary_rows.append(
            {
                "outer_fold": int(outer_fold_id),
                "stage": "A",
                "word_max_features": combo[0], "char_max_features": combo[1],
                "word_min_df": combo[2], "char_min_df": combo[3], "svd_n_components": combo[4],
                "inner_pooled_pr_auc": float(average_precision_score(pooled["label"], pooled["y_score"])),
            }
        )
    summary_df = pd.DataFrame(summary_rows)
    ordered = summary_df.sort_values(
        ["inner_pooled_pr_auc", "word_max_features", "svd_n_components"], ascending=[False, True, True], kind="stable"
    ).reset_index(drop=True)
    best = ordered.iloc[0]
    best_combo = (
        int(best["word_max_features"]), int(best["char_max_features"]),
        int(best["word_min_df"]), int(best["char_min_df"]), int(best["svd_n_components"]),
    )
    return summary_df, {"combo": best_combo, "inner_pooled_pr_auc": float(best["inner_pooled_pr_auc"]), "frames": frames}


def _stage_b_search(
    frames: list[tuple[pd.DataFrame, pd.DataFrame]],
    static_lookup: pd.DataFrame,
    best_combo: tuple,
    outer_fold_id: int,
    config: Exp2Config,
) -> tuple[pd.DataFrame, dict]:
    """Select MLP architecture + learning rate, refitting Stage A's winning representation once per inner fold."""
    arch_combos = list(itertools.product(config.hidden_dim_1_grid, config.hidden_dim_2_grid, config.learning_rate_grid))
    predictions_by_combo: dict[tuple, list[pd.DataFrame]] = {combo: [] for combo in arch_combos}

    for inner_fold_id, (fit_frame, valid_frame) in enumerate(frames):
        x_fit, y_fit, x_valid, y_valid, valid_ids = _build_combo_features(
            fit_frame, valid_frame, static_lookup, config, best_combo, outer_fold_id
        )
        for hidden_1, hidden_2, lr in arch_combos:
            _, _, valid_scores, _ = _train_mlp_with_early_stopping(
                x_fit, y_fit, x_valid, y_valid, config, hidden_1, hidden_2, lr,
                fold_seed=config.random_state + 7_000 + outer_fold_id * 100 + inner_fold_id,
            )
            predictions_by_combo[(hidden_1, hidden_2, lr)].append(
                pd.DataFrame({"source_row_id": valid_ids, "label": y_valid, "y_score": valid_scores})
            )
        del x_fit, x_valid
        gc.collect()

    summary_rows = []
    for combo in arch_combos:
        pooled = pd.concat(predictions_by_combo[combo], ignore_index=True)
        summary_rows.append(
            {
                "outer_fold": int(outer_fold_id), "stage": "B",
                "hidden_dim_1": combo[0], "hidden_dim_2": combo[1], "learning_rate": combo[2],
                "inner_pooled_pr_auc": float(average_precision_score(pooled["label"], pooled["y_score"])),
            }
        )
    summary_df = pd.DataFrame(summary_rows)
    ordered = summary_df.sort_values(
        ["inner_pooled_pr_auc", "hidden_dim_1", "hidden_dim_2"], ascending=[False, True, True], kind="stable"
    ).reset_index(drop=True)
    best = ordered.iloc[0]
    best_predictions = pd.concat(
        predictions_by_combo[(int(best["hidden_dim_1"]), int(best["hidden_dim_2"]), float(best["learning_rate"]))],
        ignore_index=True,
    )
    selection = {
        "hidden_dim_1": int(best["hidden_dim_1"]), "hidden_dim_2": int(best["hidden_dim_2"]),
        "learning_rate": float(best["learning_rate"]), "inner_pooled_pr_auc": float(best["inner_pooled_pr_auc"]),
    }
    return summary_df, {"selection": selection, "predictions": best_predictions}


def _run_inner_search(outer_train_frame: pd.DataFrame, static_lookup: pd.DataFrame, outer_fold_id: int, config: Exp2Config) -> tuple[pd.DataFrame, dict]:
    """Run Stage A then Stage B and pick the decision threshold from the winning configuration's pooled inner scores."""
    outer_label = f"Outer fold {outer_fold_id + 1}/{config.n_splits}"
    _log(f"{outer_label} | Stage A (representation) search started.", config.verbose)
    stage_a_summary, stage_a_best = _stage_a_search(outer_train_frame, static_lookup, outer_fold_id, config)

    _log(f"{outer_label} | Stage B (architecture) search started.", config.verbose)
    stage_b_summary, stage_b_best = _stage_b_search(
        stage_a_best["frames"], static_lookup, stage_a_best["combo"], outer_fold_id, config
    )

    selected_threshold, threshold_metrics = select_f1_threshold(
        labels=stage_b_best["predictions"]["label"], scores=stage_b_best["predictions"]["y_score"]
    )

    word_mf, char_mf, word_md, char_md, svd_components = stage_a_best["combo"]
    selection = {
        "outer_fold": int(outer_fold_id),
        "word_max_features": word_mf, "char_max_features": char_mf,
        "word_min_df": word_md, "char_min_df": char_md, "svd_n_components": svd_components,
        "hidden_dim_1": stage_b_best["selection"]["hidden_dim_1"],
        "hidden_dim_2": stage_b_best["selection"]["hidden_dim_2"],
        "learning_rate": stage_b_best["selection"]["learning_rate"],
        "decision_threshold": selected_threshold,
        "inner_pooled_pr_auc": stage_b_best["selection"]["inner_pooled_pr_auc"],
        "inner_validation_f1": float(threshold_metrics["f1"]),
    }
    _log(
        f"{outer_label} | selected max_features=({word_mf},{char_mf}) min_df=({word_md},{char_md}) "
        f"svd={svd_components} hidden=({selection['hidden_dim_1']},{selection['hidden_dim_2']}) "
        f"lr={selection['learning_rate']:g} threshold={selected_threshold:.2f} "
        f"(inner PR-AUC={selection['inner_pooled_pr_auc']:.4f}).",
        config.verbose,
    )
    del stage_a_best["frames"]
    gc.collect()
    return pd.concat([stage_a_summary, stage_b_summary], ignore_index=True, sort=False), selection


def _fit_outer_fold(
    outer_train_frame: pd.DataFrame,
    outer_test_frame: pd.DataFrame,
    static_lookup: pd.DataFrame,
    outer_fold_id: int,
    selection: dict,
    config: Exp2Config,
) -> tuple[pd.DataFrame, dict, pd.DataFrame]:
    """Refit the selected configuration on the full outer-train fold and score the outer-test fold once."""
    outer_label = f"Outer fold {outer_fold_id + 1}/{config.n_splits}"
    fold_start = time.perf_counter()

    fit_idx, valid_idx = _inner_splits(outer_train_frame, config, outer_fold_id)[0]
    fit_frame = outer_train_frame.iloc[fit_idx].reset_index(drop=True)
    valid_frame = outer_train_frame.iloc[valid_idx].reset_index(drop=True)

    x_fit_lex, x_test_lex, lexical_metadata = _fit_lexical_matrices(
        fit_frame[config.code_column], outer_test_frame[config.code_column], config,
        selection["word_max_features"], selection["char_max_features"], selection["word_min_df"], selection["char_min_df"],
    )
    _, x_valid_lex, _ = _fit_lexical_matrices(
        fit_frame[config.code_column], valid_frame[config.code_column], config,
        selection["word_max_features"], selection["char_max_features"], selection["word_min_df"], selection["char_min_df"],
    )

    svd = TruncatedSVD(
        n_components=selection["svd_n_components"], algorithm=config.svd_algorithm,
        n_iter=config.svd_n_iter, n_oversamples=config.svd_n_oversamples, random_state=config.random_state + outer_fold_id,
    )
    x_fit_svd = np.asarray(svd.fit_transform(x_fit_lex), dtype=np.float32)
    x_valid_svd = np.asarray(svd.transform(x_valid_lex), dtype=np.float32)
    x_test_svd = np.asarray(svd.transform(x_test_lex), dtype=np.float32)

    x_fit_static = _get_static_matrix(static_lookup, fit_frame[config.source_id_column])
    x_valid_static = _get_static_matrix(static_lookup, valid_frame[config.source_id_column])
    x_test_static = _get_static_matrix(static_lookup, outer_test_frame[config.source_id_column])

    x_fit = np.hstack([x_fit_svd, x_fit_static]).astype(np.float32, copy=False)
    x_valid = np.hstack([x_valid_svd, x_valid_static]).astype(np.float32, copy=False)
    x_test = np.hstack([x_test_svd, x_test_static]).astype(np.float32, copy=False)
    x_fit, x_valid, x_test = _fit_scaler_and_transform(x_fit, x_valid, x_test)

    y_fit = fit_frame[config.label_column].to_numpy(dtype=np.int8)
    y_valid = valid_frame[config.label_column].to_numpy(dtype=np.int8)

    model, mlp_metadata, _, device = _train_mlp_with_early_stopping(
        x_fit, y_fit, x_valid, y_valid, config,
        selection["hidden_dim_1"], selection["hidden_dim_2"], selection["learning_rate"],
        fold_seed=config.random_state + 1_000 + outer_fold_id, record_history=True,
    )
    training_history = mlp_metadata.pop("training_history")
    training_history.insert(0, "fold", int(outer_fold_id))

    batch_size = config.batch_size_gpu if device.type == "cuda" else config.batch_size_cpu
    y_score = _predict_scores(model, x_test, device, batch_size, config)

    predictions = outer_test_frame[
        [config.source_id_column, config.fold_column, config.label_column, config.project_column]
    ].copy().rename(
        columns={
            config.source_id_column: "source_row_id", config.fold_column: "fold",
            config.label_column: "label", config.project_column: "project",
        }
    )
    predictions["y_score"] = y_score.astype(np.float64)

    total_seconds = float(time.perf_counter() - fold_start)
    training_metadata = {
        "fold": int(outer_fold_id),
        "train_rows": int(len(outer_train_frame)), "test_rows": int(len(outer_test_frame)),
        "train_positive_rate": float(outer_train_frame[config.label_column].mean()),
        "test_positive_rate": float(outer_test_frame[config.label_column].mean()),
        **selection,
        **lexical_metadata,
        **mlp_metadata,
        "total_fold_seconds": total_seconds,
    }
    _log(f"{outer_label} | fit+scored in {_format_seconds(total_seconds)}.", config.verbose)

    del x_fit_lex, x_valid_lex, x_test_lex, x_fit_svd, x_valid_svd, x_test_svd, x_fit, x_valid, x_test, model
    if device.type == "cuda":
        torch.cuda.empty_cache()
    gc.collect()
    return predictions, training_metadata, training_history


def run_exp2_profile_fold(
    normalized_frame: pd.DataFrame,
    static_features_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    fold_id: int = 0,
    config: Exp2Config = Exp2Config(),
) -> dict:
    """Run the inner search plus refit for exactly ONE outer fold, to check feasibility before the full 5-fold run."""
    _validate_config(config)
    if fold_id not in range(config.n_splits):
        raise ValueError(f"fold_id must be in [0, {config.n_splits - 1}], got {fold_id}.")

    _log(f"CS1-EXP2 profiling mode: running outer fold {fold_id + 1}/{config.n_splits} only.", config.verbose)
    dataset, static_lookup = _prepare_dataset_and_static_lookup(normalized_frame, static_features_frame, manifest, config)
    train_frame = dataset.loc[dataset[config.fold_column] != fold_id].reset_index(drop=True)
    test_frame = dataset.loc[dataset[config.fold_column] == fold_id].reset_index(drop=True)

    inner_summary, selection = _run_inner_search(train_frame, static_lookup, fold_id, config)
    predictions, training_metadata, training_history = _fit_outer_fold(train_frame, test_frame, static_lookup, fold_id, selection, config)
    profile_metrics = compute_binary_metrics(predictions["label"], predictions["y_score"], threshold=selection["decision_threshold"])

    del train_frame, test_frame, dataset, static_lookup
    gc.collect()
    return {
        "fold_id": int(fold_id), "predictions": predictions, "inner_search": inner_summary,
        "selection": selection, "training_metadata": pd.DataFrame([training_metadata]),
        "training_history": training_history, "profile_metrics": profile_metrics,
    }


def _safe_experiment_name(name: str) -> str:
    """Filesystem-safe slug for artifact filenames."""
    lowered = name.strip().lower().replace(" ", "_")
    return "".join(char if char.isalnum() or char in {"_", "-"} else "_" for char in lowered)


def _save_exp2_artifacts(results: Mapping[str, object], output_dir: Path | str, config: Exp2Config, additional_metadata: Optional[Mapping[str, object]] = None) -> Exp2Artifacts:
    """Save complete EXP-2 artifacts plus shared evaluation outputs."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    oof_predictions, fold_training, inner_search, training_history, evaluation = (
        results["oof_predictions"], results["fold_training"], results["inner_search"],
        results["training_history"], results["evaluation"]
    )
    safe_name = _safe_experiment_name(config.experiment_name)
    config_json = output_dir / f"{safe_name}_config.json"
    fold_training_csv = output_dir / f"{safe_name}_fold_training.csv"
    inner_search_csv = output_dir / f"{safe_name}_inner_search.csv"
    training_history_csv = output_dir / f"{safe_name}_training_history.csv"
    run_metadata_json = output_dir / f"{safe_name}_run_metadata.json"

    with config_json.open("w", encoding="utf-8") as file:
        json.dump({"exp2_version": EXP2_VERSION, "config": asdict(config)}, file, indent=2)
    fold_training.to_csv(fold_training_csv, index=False)
    inner_search.to_csv(inner_search_csv, index=False)
    training_history.to_csv(training_history_csv, index=False)

    evaluation_paths = save_evaluation_artifacts(
        evaluation=evaluation, output_dir=output_dir, experiment_name=config.experiment_name,
        config=EvaluationConfig(threshold=float(fold_training["decision_threshold"].mean()), expected_n_folds=config.n_splits),
        additional_metadata={
            "exp2_version": EXP2_VERSION,
            "model": "PyTorch shallow MLP (SVD+static -> hidden_1 -> hidden_2 -> 1) with AdamW",
            "representation": "outer-train-only word/char TF-IDF, TruncatedSVD, and 54 static features; capacity/architecture selected per outer fold via staged inner CV",
            "score_interpretation": "Sigmoid risk score; not a calibrated real-world probability.",
            **dict(additional_metadata or {}),
        },
    )

    run_metadata = {
        "exp2_version": EXP2_VERSION,
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "experiment_name": config.experiment_name,
        "config": asdict(config),
        "n_oof_predictions": int(len(oof_predictions)),
        "folds_completed": sorted(oof_predictions["fold"].unique().astype(int).tolist()),
        "selected_hyperparameters_by_fold": fold_training[
            ["fold", "word_max_features", "char_max_features", "word_min_df", "char_min_df",
             "svd_n_components", "hidden_dim_1", "hidden_dim_2", "learning_rate", "decision_threshold"]
        ].to_dict(orient="records"),
        "additional_metadata": dict(additional_metadata or {}),
    }
    with run_metadata_json.open("w", encoding="utf-8") as file:
        json.dump(run_metadata, file, indent=2, default=str)

    return Exp2Artifacts(
        config_json=config_json, fold_training_csv=fold_training_csv, inner_search_csv=inner_search_csv,
        training_history_csv=training_history_csv, run_metadata_json=run_metadata_json, evaluation_paths=evaluation_paths,
    )


def run_exp2(
    normalized_frame: pd.DataFrame,
    static_features_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    config: Exp2Config = Exp2Config(),
    output_dir: Optional[Path | str] = None,
    additional_metadata: Optional[Mapping[str, object]] = None,
) -> dict:
    """Run the official rotating 5-fold CS1-EXP2-MLP experiment, with a staged inner-CV search per outer fold."""
    _validate_config(config)
    _log(f"CS1-EXP2 official run started: {config.n_splits} rotating outer folds.", config.verbose)

    dataset, static_lookup = _prepare_dataset_and_static_lookup(normalized_frame, static_features_frame, manifest, config)

    all_predictions: list[pd.DataFrame] = []
    all_inner_search: list[pd.DataFrame] = []
    all_training_history: list[pd.DataFrame] = []
    training_rows: list[dict] = []
    run_start = time.perf_counter()

    for fold_id in range(config.n_splits):
        train_frame = dataset.loc[dataset[config.fold_column] != fold_id].reset_index(drop=True)
        test_frame = dataset.loc[dataset[config.fold_column] == fold_id].reset_index(drop=True)
        if train_frame.empty or test_frame.empty:
            raise RuntimeError(f"Fold {fold_id} has an empty train/test partition.")

        inner_summary, selection = _run_inner_search(train_frame, static_lookup, fold_id, config)
        fold_predictions, fold_metadata, fold_history = _fit_outer_fold(train_frame, test_frame, static_lookup, fold_id, selection, config)

        all_predictions.append(fold_predictions)
        all_inner_search.append(inner_summary)
        all_training_history.append(fold_history)
        training_rows.append(fold_metadata)
        del train_frame, test_frame
        gc.collect()

    oof_predictions = pd.concat(all_predictions, ignore_index=True).sort_values("source_row_id", kind="stable").reset_index(drop=True)
    fold_training = pd.DataFrame(training_rows).sort_values("fold").reset_index(drop=True)
    inner_search = pd.concat(all_inner_search, ignore_index=True).sort_values(["outer_fold", "stage", "inner_pooled_pr_auc"], ascending=[True, True, False]).reset_index(drop=True)
    training_history = pd.concat(all_training_history, ignore_index=True).sort_values(["fold", "epoch"]).reset_index(drop=True)

    if len(oof_predictions) != len(dataset):
        raise RuntimeError(f"OOF prediction count mismatch: {len(oof_predictions):,} vs {len(dataset):,}.")
    if oof_predictions["source_row_id"].duplicated().any():
        raise RuntimeError("Duplicate source_row_id found in OOF predictions.")

    mean_threshold = float(fold_training["decision_threshold"].mean())
    evaluation = evaluate_oof_predictions(oof_predictions, config=EvaluationConfig(threshold=mean_threshold, expected_n_folds=config.n_splits))

    total_runtime_seconds = float(time.perf_counter() - run_start)
    _log(f"CS1-EXP2 official run completed in {_format_seconds(total_runtime_seconds)}.", config.verbose)

    results = {
        "oof_predictions": evaluation["predictions"], "fold_training": fold_training,
        "inner_search": inner_search, "training_history": training_history,
        "evaluation": evaluation, "total_runtime_seconds": total_runtime_seconds,
    }
    if output_dir is not None:
        results["artifacts"] = _save_exp2_artifacts(results, output_dir, config, additional_metadata)
        _log(f"Artifacts saved to: {Path(output_dir)}", config.verbose)
    return results


__all__ = [
    "EXP2_VERSION",
    "Exp2Artifacts",
    "Exp2Config",
    "run_exp2",
    "run_exp2_profile_fold",
]
