"""
CS1-EXP0: word + character TF-IDF with class-weighted SGD Logistic Regression.

This module implements the first Case Study 1 experiment:

    normalized C/C++ function text
        -> word TF-IDF, n-grams (1, 3)
        +  character TF-IDF, n-grams (3, 4)
        -> sparse feature union
        -> class-weighted L2 Logistic Regression trained with SGD
        -> 5-fold project-aware development out-of-fold predictions

The module has two execution modes:
1. run_exp0_profile_fold(...)
   Runs ONE held-out fold with detailed timing. Use this first to check whether
   the declared CPU configuration is practical in Google Colab.
2. run_exp0(...)
   Runs the complete five-fold development-CV experiment only after profiling is acceptable.
3. run_exp0_final_holdout(...)
   Fits one final model on all development projects and scores the frozen,
   project-disjoint outer holdout exactly once.

Leakage control
---------------
For every fold, both TF-IDF vectorizers are fitted only on the training
partition. The held-out project fold is transformed using the training
vocabulary/IDF statistics only.

Interpretation
--------------
Because class_weight="balanced" is used, y_score is best treated as a
vulnerability-risk ranking score. It is not yet a calibrated probability.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import gc
import json
from pathlib import Path
import time
import warnings
from typing import Mapping, Optional, Sequence

import numpy as np
import pandas as pd
from scipy.sparse import hstack
from sklearn.exceptions import ConvergenceWarning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import SGDClassifier

from ..evaluation import (
    EvaluationConfig,
    compute_binary_metrics,
    evaluate_oof_predictions,
    save_evaluation_artifacts,
)
from ..split_manifest import (
    SplitConfig,
    apply_manifest,
    assert_manifest_integrity,
)


EXP0_VERSION = "cs1-exp0-sgd-logistic-v2-holdout-innercv"


@dataclass(frozen=True)
class Exp0Config:
    """Declared reproducible configuration for CS1-EXP0-LR."""

    experiment_name: str = "cs1_exp0_lr"
    code_column: str = "normalized_code"
    source_id_column: str = "source_row_id"
    label_column: str = "label"
    project_column: str = "project"
    fold_column: str = "fold"

    n_splits: int = 5
    random_state: int = 42
    decision_threshold: float = 0.50

    # Word TF-IDF: identifiers, API calls, and local lexical sequences.
    word_ngram_range: tuple[int, int] = (1, 3)
    word_min_df: int = 3
    word_max_df: float = 0.995
    word_max_features: int = 50_000

    # Character TF-IDF: punctuation, pointer/array patterns, and partial tokens.
    char_analyzer: str = "char"
    char_ngram_range: tuple[int, int] = (3, 4)
    char_min_df: int = 8
    char_max_df: float = 0.995
    char_max_features: int = 60_000

    lowercase: bool = False
    sublinear_tf: bool = True
    tfidf_norm: str = "l2"

    # SGD-based binary Logistic Regression: scalable for sparse TF-IDF.
    # loss="log_loss" is logistic regression trained via stochastic gradient descent.
    sgd_loss: str = "log_loss"
    sgd_penalty: str = "l2"
    sgd_alpha: float = 1e-5
    sgd_class_weight: str = "balanced"
    sgd_max_iter: int = 80
    sgd_tol: float = 1e-3
    sgd_average: bool = True

    top_features_per_direction: int = 30
    verbose: bool = True


@dataclass(frozen=True)
class Exp0Artifacts:
    """Artifacts generated by a complete official EXP-0 run."""

    config_json: Path
    fold_training_csv: Path
    top_features_csv: Path
    run_metadata_json: Path
    evaluation_paths: object


def _log(message: str, enabled: bool = True) -> None:
    """Print an immediate timestamped progress message when verbose mode is enabled."""
    if enabled:
        timestamp = datetime.now().strftime("%H:%M:%S")
        print(f"[{timestamp}] {message}", flush=True)


def _format_seconds(seconds: float) -> str:
    """Human-readable elapsed time."""
    seconds = float(seconds)
    if seconds < 60:
        return f"{seconds:.1f}s"
    return f"{seconds / 60:.2f} min"


def _validate_config(config: Exp0Config) -> None:
    if config.n_splits < 2:
        raise ValueError("n_splits must be >= 2.")
    if not 0.0 < float(config.decision_threshold) < 1.0:
        raise ValueError("decision_threshold must lie strictly between 0 and 1.")
    if config.word_ngram_range[0] < 1 or config.word_ngram_range[1] < config.word_ngram_range[0]:
        raise ValueError("word_ngram_range must be a valid positive interval.")
    if config.char_ngram_range[0] < 1 or config.char_ngram_range[1] < config.char_ngram_range[0]:
        raise ValueError("char_ngram_range must be a valid positive interval.")
    if config.word_min_df < 1 or config.char_min_df < 1:
        raise ValueError("word_min_df and char_min_df must be >= 1.")
    if config.word_max_features < 1 or config.char_max_features < 1:
        raise ValueError("word_max_features and char_max_features must be >= 1.")
    if config.sgd_loss != "log_loss":
        raise ValueError("CS1-EXP0 requires sgd_loss='log_loss' for Logistic Regression.")
    if config.sgd_penalty != "l2":
        raise ValueError("CS1-EXP0 requires sgd_penalty='l2' for the declared baseline.")
    if config.sgd_alpha <= 0:
        raise ValueError("sgd_alpha must be > 0.")
    if config.sgd_max_iter < 1:
        raise ValueError("sgd_max_iter must be >= 1.")
    if config.sgd_tol <= 0:
        raise ValueError("sgd_tol must be > 0.")


def _require_columns(frame: pd.DataFrame, columns: Sequence[str]) -> None:
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        raise KeyError(
            f"Missing required column(s): {missing}. "
            f"Available columns: {sorted(frame.columns.tolist())}"
        )


def _validate_experiment_frame(frame: pd.DataFrame, config: Exp0Config) -> pd.DataFrame:
    """Validate the normalized data after its fixed fold assignment is attached."""
    _require_columns(
        frame,
        [
            config.source_id_column,
            config.code_column,
            config.label_column,
            config.project_column,
            config.fold_column,
        ],
    )

    checked = frame.copy()

    if checked[config.source_id_column].isna().any():
        raise ValueError("source_row_id contains missing values.")
    if checked[config.source_id_column].duplicated().any():
        raise ValueError("source_row_id contains duplicate values.")

    checked[config.code_column] = checked[config.code_column].fillna("").astype(str)
    empty_code = checked[config.code_column].str.strip() == ""
    if empty_code.any():
        raise ValueError(
            f"{int(empty_code.sum()):,} rows contain empty normalized code. "
            "Use the normalized cache that passed the prior quality gate."
        )

    labels = pd.to_numeric(checked[config.label_column], errors="raise")
    if not labels.isin([0, 1]).all():
        raise ValueError("label must contain exactly binary values 0 and 1.")
    checked[config.label_column] = labels.astype("int8")

    checked[config.project_column] = (
        checked[config.project_column].fillna("").astype(str).str.strip()
    )
    if (checked[config.project_column] == "").any():
        raise ValueError("project contains missing or empty identifiers.")

    folds = pd.to_numeric(checked[config.fold_column], errors="raise").astype(int)
    expected = set(range(config.n_splits))
    observed = set(folds.unique().tolist())
    if observed != expected:
        raise ValueError(f"Expected folds {sorted(expected)}, observed {sorted(observed)}.")
    checked[config.fold_column] = folds.astype("int8")

    return checked


def _build_word_vectorizer(config: Exp0Config) -> TfidfVectorizer:
    """
    Word TF-IDF with a custom token pattern that retains one-character tokens
    such as i and x. Default sklearn tokenization would discard them.
    """
    return TfidfVectorizer(
        analyzer="word",
        token_pattern=r"(?u)\b\w+\b",
        ngram_range=config.word_ngram_range,
        min_df=config.word_min_df,
        max_df=config.word_max_df,
        max_features=config.word_max_features,
        lowercase=config.lowercase,
        sublinear_tf=config.sublinear_tf,
        norm=config.tfidf_norm,
        dtype=np.float32,
    )


def _build_char_vectorizer(config: Exp0Config) -> TfidfVectorizer:
    """
    Character TF-IDF over raw source text.

    analyzer='char' intentionally captures C/C++ syntax patterns crossing
    token boundaries, including ->, [], *, &, casts, and fragments of APIs.
    """
    return TfidfVectorizer(
        analyzer=config.char_analyzer,
        ngram_range=config.char_ngram_range,
        min_df=config.char_min_df,
        max_df=config.char_max_df,
        max_features=config.char_max_features,
        lowercase=config.lowercase,
        sublinear_tf=config.sublinear_tf,
        norm=config.tfidf_norm,
        dtype=np.float32,
    )


def _build_model(config: Exp0Config) -> SGDClassifier:
    """Construct scalable L2 Logistic Regression trained with SGD."""
    return SGDClassifier(
        loss=config.sgd_loss,
        penalty=config.sgd_penalty,
        alpha=config.sgd_alpha,
        class_weight=config.sgd_class_weight,
        max_iter=config.sgd_max_iter,
        tol=config.sgd_tol,
        average=config.sgd_average,
        shuffle=True,
        random_state=config.random_state,
    )


def _fit_and_transform_fold(
    train_code: pd.Series,
    test_code: pd.Series,
    config: Exp0Config,
    fold_id: int,
):
    """
    Fit train-only word and character vectorizers and transform train/test code.

    Detailed stage timings are returned so Colab runs can be profiled.
    """
    fold_label = (
        "FINAL HOLDOUT"
        if fold_id < 0
        else f"Fold {fold_id + 1}/{config.n_splits}"
    )

    word_vectorizer = _build_word_vectorizer(config)
    char_vectorizer = _build_char_vectorizer(config)

    _log(f"{fold_label} | fitting word TF-IDF...", config.verbose)
    word_start = time.perf_counter()
    x_train_word = word_vectorizer.fit_transform(train_code)
    x_test_word = word_vectorizer.transform(test_code)
    word_seconds = float(time.perf_counter() - word_start)
    _log(
        f"{fold_label} | word TF-IDF done in {_format_seconds(word_seconds)} "
        f"({len(word_vectorizer.get_feature_names_out()):,} features).",
        config.verbose,
    )

    _log(f"{fold_label} | fitting character TF-IDF...", config.verbose)
    char_start = time.perf_counter()
    x_train_char = char_vectorizer.fit_transform(train_code)
    x_test_char = char_vectorizer.transform(test_code)
    char_seconds = float(time.perf_counter() - char_start)
    _log(
        f"{fold_label} | character TF-IDF done in {_format_seconds(char_seconds)} "
        f"({len(char_vectorizer.get_feature_names_out()):,} features).",
        config.verbose,
    )

    _log(f"{fold_label} | joining sparse feature matrices...", config.verbose)
    join_start = time.perf_counter()
    x_train = hstack([x_train_word, x_train_char], format="csr", dtype=np.float32)
    x_test = hstack([x_test_word, x_test_char], format="csr", dtype=np.float32)
    join_seconds = float(time.perf_counter() - join_start)
    _log(
        f"{fold_label} | sparse matrices ready in {_format_seconds(join_seconds)} "
        f"(total features: {x_train.shape[1]:,}).",
        config.verbose,
    )

    metadata = {
        "word_tfidf_seconds": word_seconds,
        "char_tfidf_seconds": char_seconds,
        "sparse_join_seconds": join_seconds,
        "vectorization_seconds": word_seconds + char_seconds + join_seconds,
        "word_features": int(len(word_vectorizer.get_feature_names_out())),
        "char_features": int(len(char_vectorizer.get_feature_names_out())),
        "total_features": int(x_train.shape[1]),
        "train_nonzero_entries": int(x_train.nnz),
        "test_nonzero_entries": int(x_test.nnz),
        "train_matrix_density": float(x_train.nnz / (x_train.shape[0] * x_train.shape[1])),
        "test_matrix_density": float(x_test.nnz / (x_test.shape[0] * x_test.shape[1])),
    }

    del x_train_word, x_test_word, x_train_char, x_test_char
    gc.collect()

    return x_train, x_test, word_vectorizer, char_vectorizer, metadata


def _top_feature_rows(
    model: SGDClassifier,
    word_vectorizer: TfidfVectorizer,
    char_vectorizer: TfidfVectorizer,
    fold_id: int,
    top_n: int,
) -> pd.DataFrame:
    """
    Return positive/negative LR coefficients for model-level interpretation.

    Positive = associated with the vulnerable label in that fold's training data.
    Negative = associated with the non-vulnerable label.
    Associations are not causal claims.
    """
    coefficients = np.asarray(model.coef_).reshape(-1)
    word_features = word_vectorizer.get_feature_names_out().astype(str)
    char_features = char_vectorizer.get_feature_names_out().astype(str)

    feature_names = np.concatenate(
        [
            np.char.add("word::", word_features),
            np.char.add("char::", char_features),
        ]
    )
    feature_types = np.concatenate(
        [
            np.repeat("word", len(word_features)),
            np.repeat("char", len(char_features)),
        ]
    )

    if len(coefficients) != len(feature_names):
        raise RuntimeError(
            "Feature/coefficient mismatch: "
            f"{len(feature_names):,} features vs {len(coefficients):,} coefficients."
        )

    top_n = min(max(0, int(top_n)), len(coefficients))
    columns = [
        "fold",
        "direction",
        "rank",
        "feature_type",
        "feature",
        "coefficient",
        "abs_coefficient",
    ]
    if top_n == 0:
        return pd.DataFrame(columns=columns)

    positive_indices = np.argsort(coefficients)[-top_n:][::-1]
    negative_indices = np.argsort(coefficients)[:top_n]

    rows: list[dict] = []
    for direction, indices in (
        ("vulnerable_associated", positive_indices),
        ("non_vulnerable_associated", negative_indices),
    ):
        for rank, index in enumerate(indices, start=1):
            rows.append(
                {
                    "fold": int(fold_id),
                    "direction": direction,
                    "rank": int(rank),
                    "feature_type": str(feature_types[index]),
                    "feature": str(feature_names[index]),
                    "coefficient": float(coefficients[index]),
                    "abs_coefficient": float(abs(coefficients[index])),
                }
            )
    return pd.DataFrame(rows, columns=columns)


def _run_single_fold(
    train_frame: pd.DataFrame,
    test_frame: pd.DataFrame,
    fold_id: int,
    config: Exp0Config,
) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    """Fit a model on one fold and return held-out predictions, explanations, and timings."""
    fold_label = (
        "FINAL HOLDOUT"
        if fold_id < 0
        else f"Fold {fold_id + 1}/{config.n_splits}"
    )
    fold_start = time.perf_counter()

    _log(
        f"{fold_label} started | train={len(train_frame):,}, test={len(test_frame):,}, "
        f"train projects={train_frame[config.project_column].nunique():,}, "
        f"test projects={test_frame[config.project_column].nunique():,}.",
        config.verbose,
    )

    x_train, x_test, word_vectorizer, char_vectorizer, vector_metadata = (
        _fit_and_transform_fold(
            train_code=train_frame[config.code_column],
            test_code=test_frame[config.code_column],
            config=config,
            fold_id=fold_id,
        )
    )

    y_train = train_frame[config.label_column].to_numpy(dtype=np.int8)
    model = _build_model(config)

    _log(
        f"{fold_label} | training SGD Logistic Regression "
        f"(loss={config.sgd_loss}, max_iter={config.sgd_max_iter}, "
        f"alpha={config.sgd_alpha:g})...",
        config.verbose,
    )
    fit_start = time.perf_counter()
    convergence_messages: list[str] = []

    with warnings.catch_warnings(record=True) as caught_warnings:
        warnings.simplefilter("always", ConvergenceWarning)
        model.fit(x_train, y_train)

    for warning_record in caught_warnings:
        if issubclass(warning_record.category, ConvergenceWarning):
            convergence_messages.append(str(warning_record.message))

    fit_seconds = float(time.perf_counter() - fit_start)
    _log(
        f"{fold_label} | SGD Logistic Regression done in {_format_seconds(fit_seconds)} "
        f"(epochs={int(model.n_iter_)}, "
        f"convergence warnings={len(convergence_messages)}).",
        config.verbose,
    )

    _log(f"{fold_label} | scoring held-out projects...", config.verbose)
    prediction_start = time.perf_counter()
    positive_class_indices = np.where(model.classes_ == 1)[0]
    if len(positive_class_indices) != 1:
        raise RuntimeError("The fitted SGD model does not expose class label 1.")
    y_score = model.predict_proba(x_test)[:, int(positive_class_indices[0])]
    prediction_seconds = float(time.perf_counter() - prediction_start)
    _log(
        f"{fold_label} | scoring done in {_format_seconds(prediction_seconds)}.",
        config.verbose,
    )

    prediction_frame = test_frame[
        [
            config.source_id_column,
            config.fold_column,
            config.label_column,
            config.project_column,
        ]
    ].copy()
    prediction_frame = prediction_frame.rename(
        columns={
            config.source_id_column: "source_row_id",
            config.fold_column: "fold",
            config.label_column: "label",
            config.project_column: "project",
        }
    )
    prediction_frame["y_score"] = y_score.astype(np.float64)

    top_features = _top_feature_rows(
        model=model,
        word_vectorizer=word_vectorizer,
        char_vectorizer=char_vectorizer,
        fold_id=fold_id,
        top_n=config.top_features_per_direction,
    )

    total_fold_seconds = float(time.perf_counter() - fold_start)
    training_metadata = {
        "fold": int(fold_id),
        "train_rows": int(len(train_frame)),
        "test_rows": int(len(test_frame)),
        "train_vulnerable": int((train_frame[config.label_column] == 1).sum()),
        "test_vulnerable": int((test_frame[config.label_column] == 1).sum()),
        "train_positive_rate": float(train_frame[config.label_column].mean()),
        "test_positive_rate": float(test_frame[config.label_column].mean()),
        "train_unique_projects": int(train_frame[config.project_column].nunique()),
        "test_unique_projects": int(test_frame[config.project_column].nunique()),
        **vector_metadata,
        "model_fit_seconds": fit_seconds,
        "prediction_seconds": prediction_seconds,
        "total_fold_seconds": total_fold_seconds,
        "model_n_iter": int(model.n_iter_),
        "optimizer": "SGDClassifier(loss=log_loss)",
        "convergence_warning_count": int(len(convergence_messages)),
        "convergence_warning_messages": " | ".join(convergence_messages),
        "score_min": float(np.min(y_score)),
        "score_max": float(np.max(y_score)),
        "score_mean": float(np.mean(y_score)),
    }

    _log(
        f"{fold_label} completed in {_format_seconds(total_fold_seconds)}.",
        config.verbose,
    )

    del x_train, x_test, word_vectorizer, char_vectorizer, model
    gc.collect()

    return prediction_frame, top_features, training_metadata


def _validate_fold_project_separation(frame: pd.DataFrame, config: Exp0Config) -> None:
    """Independently verify the no-project-leakage property for every fold."""
    for fold_id in range(config.n_splits):
        test_projects = set(
            frame.loc[frame[config.fold_column] == fold_id, config.project_column]
        )
        train_projects = set(
            frame.loc[frame[config.fold_column] != fold_id, config.project_column]
        )
        overlap = test_projects.intersection(train_projects)
        if overlap:
            raise ValueError(
                f"Project leakage detected in fold {fold_id}. "
                f"Examples: {sorted(overlap)[:10]}"
            )


def _prepare_dataset_with_folds(
    normalized_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    config: Exp0Config,
) -> pd.DataFrame:
    """Attach the immutable manifest and validate all EXP-0 inputs."""
    split_config = SplitConfig(
        n_splits=config.n_splits,
        random_state=config.random_state,
        shuffle=True,
    )
    assert_manifest_integrity(manifest, config=split_config)

    merged = apply_manifest(
        frame=normalized_frame,
        manifest=manifest,
        source_id_column=config.source_id_column,
    )
    merged = _validate_experiment_frame(merged, config)
    _validate_fold_project_separation(merged, config)
    return merged


def run_exp0_profile_fold(
    normalized_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    fold_id: int = 0,
    config: Exp0Config = Exp0Config(),
) -> dict:
    """
    Profile exactly ONE held-out fold before the official five-fold run.

    This function is for computational feasibility assessment. It returns
    timings, one-fold predictions, and one-fold descriptive metrics but does not
    create the complete OOF result and should not be reported as the official
    EXP-0 performance.

    Suggested first call:
        run_exp0_profile_fold(..., fold_id=0, config=exp0_config)
    """
    _validate_config(config)

    if fold_id not in range(config.n_splits):
        raise ValueError(
            f"fold_id must be in [0, {config.n_splits - 1}], received {fold_id}."
        )

    _log(
        f"CS1-EXP0 profiling mode: running Fold {fold_id + 1}/{config.n_splits} only.",
        config.verbose,
    )

    dataset_with_folds = _prepare_dataset_with_folds(
        normalized_frame=normalized_frame,
        manifest=manifest,
        config=config,
    )

    train_frame = dataset_with_folds.loc[
        dataset_with_folds[config.fold_column] != fold_id
    ].reset_index(drop=True)
    test_frame = dataset_with_folds.loc[
        dataset_with_folds[config.fold_column] == fold_id
    ].reset_index(drop=True)

    predictions, top_features, training_metadata = _run_single_fold(
        train_frame=train_frame,
        test_frame=test_frame,
        fold_id=fold_id,
        config=config,
    )

    profile_metrics = compute_binary_metrics(
        labels=predictions["label"],
        scores=predictions["y_score"],
        threshold=config.decision_threshold,
    )

    _log(
        "Profiling run complete. These metrics are descriptive for one fold only; "
        "do not treat them as the official five-fold EXP-0 result.",
        config.verbose,
    )

    del train_frame, test_frame, dataset_with_folds
    gc.collect()

    return {
        "fold_id": int(fold_id),
        "predictions": predictions,
        "top_features": top_features,
        "training_metadata": pd.DataFrame([training_metadata]),
        "profile_metrics": profile_metrics,
    }


def _save_exp0_artifacts(
    results: Mapping[str, object],
    output_dir: Path | str,
    config: Exp0Config,
    additional_metadata: Optional[Mapping[str, object]] = None,
) -> Exp0Artifacts:
    """Save complete EXP-0 artifacts plus shared evaluation outputs."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    oof_predictions = results["oof_predictions"]
    fold_training = results["fold_training"]
    top_features = results["top_features"]
    evaluation = results["evaluation"]

    if not isinstance(oof_predictions, pd.DataFrame):
        raise TypeError("oof_predictions must be a DataFrame.")
    if not isinstance(fold_training, pd.DataFrame):
        raise TypeError("fold_training must be a DataFrame.")
    if not isinstance(top_features, pd.DataFrame):
        raise TypeError("top_features must be a DataFrame.")
    if not isinstance(evaluation, Mapping):
        raise TypeError("evaluation must be a mapping.")

    safe_name = config.experiment_name.strip().lower().replace(" ", "_")
    safe_name = "".join(
        char if char.isalnum() or char in {"_", "-"} else "_"
        for char in safe_name
    )

    config_json = output_dir / f"{safe_name}_config.json"
    fold_training_csv = output_dir / f"{safe_name}_fold_training.csv"
    top_features_csv = output_dir / f"{safe_name}_top_features.csv"
    run_metadata_json = output_dir / f"{safe_name}_run_metadata.json"

    with config_json.open("w", encoding="utf-8") as file:
        json.dump(
            {"exp0_version": EXP0_VERSION, "config": asdict(config)},
            file,
            indent=2,
        )

    fold_training.to_csv(fold_training_csv, index=False)
    top_features.to_csv(top_features_csv, index=False)

    evaluation_paths = save_evaluation_artifacts(
        evaluation=evaluation,
        output_dir=output_dir,
        experiment_name=config.experiment_name,
        config=EvaluationConfig(
            threshold=config.decision_threshold,
            expected_n_folds=config.n_splits,
        ),
        additional_metadata={
            "exp0_version": EXP0_VERSION,
            "model": "class-weighted L2 Logistic Regression optimized with SGDClassifier(loss=log_loss)",
            "feature_representation": (
                "word TF-IDF ngrams (1,3) + character TF-IDF ngrams (3,4)"
            ),
            "score_interpretation": (
                "Class-weighted SGD Logistic Regression risk score; not a calibrated "
                "real-world probability."
            ),
            **dict(additional_metadata or {}),
        },
    )

    run_metadata = {
        "exp0_version": EXP0_VERSION,
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "experiment_name": config.experiment_name,
        "config": asdict(config),
        "n_oof_predictions": int(len(oof_predictions)),
        "folds_completed": sorted(oof_predictions["fold"].unique().astype(int).tolist()),
        "total_vectorization_seconds": float(fold_training["vectorization_seconds"].sum()),
        "total_model_fit_seconds": float(fold_training["model_fit_seconds"].sum()),
        "total_prediction_seconds": float(fold_training["prediction_seconds"].sum()),
        "total_runtime_seconds": float(fold_training["total_fold_seconds"].sum()),
        "folds_with_convergence_warning": int(
            (fold_training["convergence_warning_count"] > 0).sum()
        ),
        "additional_metadata": dict(additional_metadata or {}),
    }
    with run_metadata_json.open("w", encoding="utf-8") as file:
        json.dump(run_metadata, file, indent=2)

    return Exp0Artifacts(
        config_json=config_json,
        fold_training_csv=fold_training_csv,
        top_features_csv=top_features_csv,
        run_metadata_json=run_metadata_json,
        evaluation_paths=evaluation_paths,
    )


def run_exp0(
    normalized_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    config: Exp0Config = Exp0Config(),
    output_dir: Optional[Path | str] = None,
    additional_metadata: Optional[Mapping[str, object]] = None,
) -> dict:
    """
    Run the official five-fold project-aware CS1-EXP0-LR experiment.

    Use run_exp0_profile_fold first if a new configuration has not been
    computationally checked in the active Colab environment.
    """
    _validate_config(config)

    _log(
        f"CS1-EXP0 official run started: {config.n_splits}-fold grouped CV.",
        config.verbose,
    )
    _log(
        f"Configuration: word<= {config.word_max_features:,}, "
        f"char<= {config.char_max_features:,}, "
        f"optimizer=SGDClassifier(log_loss), max_iter={config.sgd_max_iter}, "
        f"alpha={config.sgd_alpha:g}.",
        config.verbose,
    )

    dataset_with_folds = _prepare_dataset_with_folds(
        normalized_frame=normalized_frame,
        manifest=manifest,
        config=config,
    )

    all_predictions: list[pd.DataFrame] = []
    all_top_features: list[pd.DataFrame] = []
    training_rows: list[dict] = []

    run_start = time.perf_counter()

    for fold_id in range(config.n_splits):
        train_frame = dataset_with_folds.loc[
            dataset_with_folds[config.fold_column] != fold_id
        ].reset_index(drop=True)
        test_frame = dataset_with_folds.loc[
            dataset_with_folds[config.fold_column] == fold_id
        ].reset_index(drop=True)

        if train_frame.empty or test_frame.empty:
            raise RuntimeError(f"Fold {fold_id} has an empty train/test partition.")
        if set(test_frame[config.label_column].unique().tolist()) != {0, 1}:
            raise RuntimeError(f"Fold {fold_id} does not contain both classes.")

        fold_predictions, fold_features, fold_metadata = _run_single_fold(
            train_frame=train_frame,
            test_frame=test_frame,
            fold_id=fold_id,
            config=config,
        )

        all_predictions.append(fold_predictions)
        all_top_features.append(fold_features)
        training_rows.append(fold_metadata)

        del train_frame, test_frame
        gc.collect()

    oof_predictions = (
        pd.concat(all_predictions, ignore_index=True)
        .sort_values("source_row_id", kind="stable")
        .reset_index(drop=True)
    )
    fold_training = pd.DataFrame(training_rows).sort_values("fold").reset_index(drop=True)
    top_features = (
        pd.concat(all_top_features, ignore_index=True)
        .sort_values(["fold", "direction", "rank"])
        .reset_index(drop=True)
    )

    if len(oof_predictions) != len(dataset_with_folds):
        raise RuntimeError(
            "OOF prediction count does not match normalized dataset size: "
            f"{len(oof_predictions):,} vs {len(dataset_with_folds):,}."
        )
    if oof_predictions["source_row_id"].duplicated().any():
        raise RuntimeError("Duplicate source_row_id found in OOF predictions.")

    evaluation = evaluate_oof_predictions(
        oof_predictions,
        config=EvaluationConfig(
            threshold=config.decision_threshold,
            expected_n_folds=config.n_splits,
        ),
    )

    total_runtime_seconds = float(time.perf_counter() - run_start)
    _log(
        f"CS1-EXP0 official run completed in {_format_seconds(total_runtime_seconds)}.",
        config.verbose,
    )

    results = {
        "oof_predictions": evaluation["predictions"],
        "fold_training": fold_training,
        "top_features": top_features,
        "evaluation": evaluation,
        "total_runtime_seconds": total_runtime_seconds,
    }

    if output_dir is not None:
        results["artifacts"] = _save_exp0_artifacts(
            results=results,
            output_dir=output_dir,
            config=config,
            additional_metadata=additional_metadata,
        )
        _log(f"Artifacts saved to: {Path(output_dir)}", config.verbose)

    return results


def _validate_final_holdout_partitions(
    dev_frame: pd.DataFrame,
    holdout_frame: pd.DataFrame,
    config: Exp0Config,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Validate two frozen final-evaluation partitions.

    The development and holdout frames must:
    - contain the expected schema;
    - have unique source IDs within and across partitions;
    - contain non-empty normalized code and project IDs;
    - contain binary labels and both classes;
    - have zero project overlap.

    This protects ``run_exp0_final_holdout`` even when it is called outside
    the notebook workflow.
    """
    required = [
        config.source_id_column,
        config.code_column,
        config.label_column,
        config.project_column,
    ]

    _require_columns(dev_frame, required)
    _require_columns(holdout_frame, required)

    dev_clean = dev_frame.copy()
    holdout_clean = holdout_frame.copy()

    for partition_name, frame in (
        ("development", dev_clean),
        ("outer holdout", holdout_clean),
    ):
        if frame.empty:
            raise ValueError(f"{partition_name} partition is empty.")

        if frame[config.source_id_column].isna().any():
            raise ValueError(
                f"{partition_name} partition contains missing source_row_id values."
            )
        if frame[config.source_id_column].duplicated().any():
            raise ValueError(
                f"{partition_name} partition contains duplicate source_row_id values."
            )

        frame[config.code_column] = frame[config.code_column].fillna("").astype(str)
        if (frame[config.code_column].str.strip() == "").any():
            empty_count = int(
                (frame[config.code_column].str.strip() == "").sum()
            )
            raise ValueError(
                f"{partition_name} partition contains {empty_count:,} empty "
                f"{config.code_column} value(s)."
            )

        frame[config.project_column] = (
            frame[config.project_column].fillna("").astype(str).str.strip()
        )
        if (frame[config.project_column] == "").any():
            raise ValueError(
                f"{partition_name} partition contains missing or empty project IDs."
            )

        labels = pd.to_numeric(frame[config.label_column], errors="raise")
        if not labels.isin([0, 1]).all():
            raise ValueError(
                f"{partition_name} labels must be binary values 0 and 1."
            )
        frame[config.label_column] = labels.astype("int8")

        if set(frame[config.label_column].unique().tolist()) != {0, 1}:
            raise ValueError(
                f"{partition_name} partition must contain both label classes."
            )

    source_id_overlap = set(dev_clean[config.source_id_column]).intersection(
        set(holdout_clean[config.source_id_column])
    )
    if source_id_overlap:
        raise RuntimeError(
            "source_row_id leakage between development and outer holdout. "
            f"Examples: {sorted(source_id_overlap)[:10]}"
        )

    project_overlap = set(dev_clean[config.project_column]).intersection(
        set(holdout_clean[config.project_column])
    )
    if project_overlap:
        raise RuntimeError(
            "Project leakage between development and outer holdout. "
            f"Examples: {sorted(project_overlap)[:10]}"
        )

    return dev_clean, holdout_clean

def run_exp0_final_holdout(
    dev_frame: pd.DataFrame,
    holdout_frame: pd.DataFrame,
    config: Exp0Config = Exp0Config(),
    output_dir: Optional[Path | str] = None,
    additional_metadata: Optional[Mapping[str, object]] = None,
) -> dict:
    """
    Fit ONE final model on the ENTIRE development partition (80%), using the
    configuration chosen via cross-validation / model selection, then score
    the untouched 20% holdout exactly once.

    Must only be called after model selection across EXP-0/EXP-1/... is
    complete. The holdout must never be used to pick a config, model, or
    threshold.
    """
    _validate_config(config)

    dev_clean, holdout_clean = _validate_final_holdout_partitions(
        dev_frame=dev_frame,
        holdout_frame=holdout_frame,
        config=config,
    )

    _log("Fitting FINAL EXP-0 model on the full development partition (80%)...", config.verbose)

    x_dev, x_holdout, word_vectorizer, char_vectorizer, vector_metadata = (
        _fit_and_transform_fold(
            train_code=dev_clean[config.code_column],
            test_code=holdout_clean[config.code_column],
            config=config,
            fold_id=-1,
        )
    )

    y_dev = dev_clean[config.label_column].to_numpy(dtype=np.int8)
    model = _build_model(config)

    fit_start = time.perf_counter()
    with warnings.catch_warnings(record=True) as caught_warnings:
        warnings.simplefilter("always", ConvergenceWarning)
        model.fit(x_dev, y_dev)
    fit_seconds = float(time.perf_counter() - fit_start)
    convergence_messages = [
        str(w.message) for w in caught_warnings if issubclass(w.category, ConvergenceWarning)
    ]

    _log("Scoring the EXP-0 HOLDOUT partition exactly once...", config.verbose)
    y_holdout = holdout_clean[config.label_column].to_numpy(dtype=np.int8)
    positive_index = np.where(model.classes_ == 1)[0]
    if len(positive_index) != 1:
        raise RuntimeError("The fitted SGD model does not expose class label 1.")
    y_score = model.predict_proba(x_holdout)[:, int(positive_index[0])]

    metrics = compute_binary_metrics(
        labels=y_holdout, scores=y_score, threshold=config.decision_threshold
    )

    predictions_df = pd.DataFrame(
        {
            "source_row_id": holdout_clean[config.source_id_column].to_numpy(),
            "label": y_holdout,
            "project": holdout_clean[config.project_column].to_numpy(),
            "y_score": y_score,
            "y_pred": (y_score >= config.decision_threshold).astype(np.int8),
        }
    )

    top_features = _top_feature_rows(
        model=model,
        word_vectorizer=word_vectorizer,
        char_vectorizer=char_vectorizer,
        fold_id=-1,
        top_n=config.top_features_per_direction,
    )

    results = {
        "experiment": "cs1_exp0_lr",
        "model": model,
        "word_vectorizer": word_vectorizer,
        "char_vectorizer": char_vectorizer,
        "predictions": predictions_df,
        "metrics": metrics,
        "top_features": top_features,
        "vector_metadata": vector_metadata,
        "fit_seconds": fit_seconds,
        "convergence_warnings": convergence_messages,
    }

    if output_dir is not None:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        safe_name = config.experiment_name.strip().lower().replace(" ", "_")
        safe_name = "".join(
            character if character.isalnum() or character in {"_", "-"} else "_"
            for character in safe_name
        )

        predictions_path = output_dir / f"{safe_name}_holdout_predictions.parquet"
        metrics_path = output_dir / f"{safe_name}_holdout_metrics.json"
        top_features_path = output_dir / f"{safe_name}_holdout_top_features.csv"
        pr_curve_path = output_dir / f"{safe_name}_holdout_precision_recall_curve.png"
        cm_path = output_dir / f"{safe_name}_holdout_confusion_matrix.png"

        predictions_df.to_parquet(predictions_path, index=False)
        top_features.to_csv(top_features_path, index=False)
        with metrics_path.open("w", encoding="utf-8") as file:
            json.dump(
                {
                    "exp0_version": EXP0_VERSION,
                    "config": asdict(config),
                    "metrics": metrics,
                    "fit_seconds": fit_seconds,
                    "n_dev_rows": int(len(dev_clean)),
                    "n_holdout_rows": int(len(holdout_clean)),
                    "additional_metadata": dict(additional_metadata or {}),
                },
                file,
                indent=2,
                default=str,
            )

        from ..evaluation import plot_precision_recall_curve, plot_confusion_matrix
        plot_precision_recall_curve(
            labels=predictions_df["label"], scores=predictions_df["y_score"],
            output_path=pr_curve_path,
            title=f"{config.experiment_name}: FINAL Holdout Precision-Recall Curve",
        )
        plot_confusion_matrix(
            labels=predictions_df["label"], predictions=predictions_df["y_pred"],
            output_path=cm_path,
            title=f"{config.experiment_name}: FINAL Holdout Confusion Matrix",
        )
        results["artifact_paths"] = {
            "predictions": predictions_path,
            "metrics": metrics_path,
            "top_features": top_features_path,
            "pr_curve": pr_curve_path,
            "confusion_matrix": cm_path,
        }
        _log(f"EXP-0 holdout artifacts saved to: {output_dir}", config.verbose)

    return results


__all__ = [
    "EXP0_VERSION",
    "Exp0Artifacts",
    "Exp0Config",
    "run_exp0",
    "run_exp0_profile_fold",
    "run_exp0_final_holdout",
]