"""
CS1-EXP1-RF: TF-IDF + TruncatedSVD + deterministic static features + Random Forest.

Pipeline per outer fold
-----------------------
1. Fit word and character TF-IDF only on training code.
2. Join sparse lexical matrices.
3. Fit TruncatedSVD only on the training sparse lexical matrix.
4. Join dense SVD vectors with cached deterministic static code features.
5. Fit a class-weighted Random Forest.
6. Score the held-out projects and collect pooled OOF predictions.

Leakage controls
----------------
- The fixed 5-fold project-aware manifest is reused unchanged.
- Word TF-IDF, character TF-IDF, and TruncatedSVD are fitted inside each
  training fold only.
- Static features are deterministic functions of each function's own source
  code. They are cached globally for efficiency but contain no labels,
  corpus-level IDF values, scaling statistics, or learned parameters.

Interpretation
--------------
- Random Forest probability scores are ranking scores for this benchmark.
  They should not be presented as calibrated real-world vulnerability
  probabilities.
- SVD components are latent lexical dimensions, not directly interpretable
  code concepts.
- Random Forest impurity importances are descriptive diagnostics only.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import gc
import json
from pathlib import Path
import time
from typing import Mapping, Optional, Sequence

import numpy as np
import pandas as pd
from scipy.sparse import hstack
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
)

from .evaluation import (
    EvaluationConfig,
    compute_binary_metrics,
    evaluate_oof_predictions,
    save_evaluation_artifacts,
)
from .split_manifest import (
    SplitConfig,
    apply_manifest,
    assert_manifest_integrity,
)
from .static_features import FEATURE_COLUMNS


EXP1_VERSION = "cs1-exp1-svd-static-rf-v2-oob-threshold"


@dataclass(frozen=True)
class Exp1Config:
    """Declared reproducible configuration for CS1-EXP1-RF."""

    experiment_name: str = "cs1_exp1_rf"
    code_column: str = "normalized_code"
    source_id_column: str = "source_row_id"
    label_column: str = "label"
    project_column: str = "project"
    fold_column: str = "fold"

    n_splits: int = 5
    random_state: int = 42
    decision_threshold: float = 0.50

    # Same lexical source representation used by EXP-0.
    word_ngram_range: tuple[int, int] = (1, 3)
    word_min_df: int = 3
    word_max_df: float = 0.995
    word_max_features: int = 50_000

    char_analyzer: str = "char"
    char_ngram_range: tuple[int, int] = (3, 4)
    char_min_df: int = 8
    char_max_df: float = 0.995
    char_max_features: int = 60_000

    lowercase: bool = False
    sublinear_tf: bool = True
    tfidf_norm: str = "l2"

    # Fit only within each training fold. 256 lexical dimensions + 54 static
    # features means each forest sees 310 dense input dimensions.
    svd_n_components: int = 256
    svd_algorithm: str = "randomized"
    svd_n_iter: int = 5
    svd_n_oversamples: int = 10

    # Random Forest configuration.
    # Profile-driven compute budget, fixed before the official run.
    rf_n_estimators: int = 200
    rf_criterion: str = "gini"
    rf_max_depth: Optional[int] = None
    rf_min_samples_split: int = 2
    rf_min_samples_leaf: int = 2
    rf_max_features: str = "sqrt"
    rf_bootstrap: bool = True
    rf_max_samples: Optional[float] = 0.70
    rf_class_weight: str = "balanced_subsample"
    rf_n_jobs: int = -1
    rf_oob_score: bool = True

    # Threshold is selected only from OOB predictions of each outer-fold
    # training partition. The held-out project data never participates.
    oob_threshold_min: float = 0.005
    oob_threshold_max: float = 0.250
    oob_threshold_step: float = 0.005
    oob_threshold_objective: str = "f1"

    feature_importance_top_n: int = 50
    verbose: bool = True


@dataclass(frozen=True)
class Exp1Artifacts:
    """Artifacts generated by a complete official EXP-1 run."""

    config_json: Path
    fold_training_csv: Path
    feature_importances_csv: Path
    static_feature_importances_csv: Path
    oob_operating_metrics_json: Path
    oob_operating_fold_metrics_csv: Path
    oob_operating_fold_summary_csv: Path
    run_metadata_json: Path
    evaluation_paths: object


def _log(message: str, enabled: bool = True) -> None:
    if enabled:
        timestamp = datetime.now().strftime("%H:%M:%S")
        print(f"[{timestamp}] {message}", flush=True)


def _format_seconds(seconds: float) -> str:
    seconds = float(seconds)
    return f"{seconds:.1f}s" if seconds < 60 else f"{seconds / 60:.2f} min"


def _require_columns(frame: pd.DataFrame, columns: Sequence[str]) -> None:
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        raise KeyError(
            f"Missing required column(s): {missing}. "
            f"Available columns: {sorted(frame.columns.tolist())}"
        )


def _validate_config(config: Exp1Config) -> None:
    if config.n_splits < 2:
        raise ValueError("n_splits must be >= 2.")
    if not 0.0 < float(config.decision_threshold) < 1.0:
        raise ValueError("decision_threshold must lie strictly between 0 and 1.")
    if config.word_min_df < 1 or config.char_min_df < 1:
        raise ValueError("word_min_df and char_min_df must be >= 1.")
    if config.word_max_features < 1 or config.char_max_features < 1:
        raise ValueError("word_max_features and char_max_features must be >= 1.")
    if config.svd_n_components < 2:
        raise ValueError("svd_n_components must be >= 2.")
    if config.svd_algorithm != "randomized":
        raise ValueError(
            "This EXP-1 implementation is declared for randomized TruncatedSVD."
        )
    if config.svd_n_iter < 1 or config.svd_n_oversamples < 1:
        raise ValueError("SVD iteration and oversampling values must be >= 1.")
    if config.rf_n_estimators < 1:
        raise ValueError("rf_n_estimators must be >= 1.")
    if config.rf_min_samples_split < 2:
        raise ValueError("rf_min_samples_split must be >= 2.")
    if config.rf_min_samples_leaf < 1:
        raise ValueError("rf_min_samples_leaf must be >= 1.")
    if config.rf_class_weight not in {"balanced", "balanced_subsample"}:
        raise ValueError(
            "rf_class_weight must be 'balanced' or 'balanced_subsample'."
        )
    if config.rf_max_samples is not None:
        if not config.rf_bootstrap:
            raise ValueError("rf_max_samples requires rf_bootstrap=True.")
        if not 0.0 < float(config.rf_max_samples) <= 1.0:
            raise ValueError("rf_max_samples must be in (0, 1] when provided.")
    if not config.rf_oob_score:
        raise ValueError(
            "EXP-1 v2 requires rf_oob_score=True for training-only threshold selection."
        )
    if not (0.0 < config.oob_threshold_min < config.oob_threshold_max < 1.0):
        raise ValueError("Invalid OOB threshold range.")
    if config.oob_threshold_step <= 0.0:
        raise ValueError("oob_threshold_step must be positive.")
    if config.oob_threshold_objective != "f1":
        raise ValueError("This implementation currently supports oob_threshold_objective='f1'.")


def _validate_dataset_with_folds(
    frame: pd.DataFrame,
    config: Exp1Config,
) -> pd.DataFrame:
    _require_columns(
        frame,
        [
            config.source_id_column,
            config.code_column,
            config.label_column,
            config.project_column,
            config.fold_column,
        ],
    )

    checked = frame.copy()
    if checked[config.source_id_column].isna().any():
        raise ValueError("source_row_id contains missing values.")
    if checked[config.source_id_column].duplicated().any():
        raise ValueError("source_row_id contains duplicate values.")

    checked[config.code_column] = checked[config.code_column].fillna("").astype(str)
    if (checked[config.code_column].str.strip() == "").any():
        raise ValueError(
            "EXP-1 received empty normalized_code rows. "
            "Use the normalized dataset that passed EXP-0 integrity checks."
        )

    labels = pd.to_numeric(checked[config.label_column], errors="raise")
    if not labels.isin([0, 1]).all():
        raise ValueError("label must contain only 0 and 1.")
    checked[config.label_column] = labels.astype("int8")

    checked[config.project_column] = (
        checked[config.project_column].fillna("").astype(str).str.strip()
    )
    if (checked[config.project_column] == "").any():
        raise ValueError("project contains missing or empty identifiers.")

    folds = pd.to_numeric(checked[config.fold_column], errors="raise").astype(int)
    expected = set(range(config.n_splits))
    if set(folds.unique().tolist()) != expected:
        raise ValueError(
            f"Expected folds {sorted(expected)}; "
            f"observed {sorted(folds.unique().tolist())}."
        )
    checked[config.fold_column] = folds.astype("int8")
    return checked


def _validate_static_feature_frame(
    static_features_frame: pd.DataFrame,
    config: Exp1Config,
) -> pd.DataFrame:
    required = [config.source_id_column] + FEATURE_COLUMNS
    _require_columns(static_features_frame, required)

    static_checked = static_features_frame[required].copy()
    if static_checked[config.source_id_column].isna().any():
        raise ValueError("Static feature cache has missing source_row_id values.")
    if static_checked[config.source_id_column].duplicated().any():
        raise ValueError("Static feature cache has duplicate source_row_id values.")

    for column in FEATURE_COLUMNS:
        static_checked[column] = pd.to_numeric(
            static_checked[column],
            errors="raise",
        ).astype(np.float32)

    values = static_checked[FEATURE_COLUMNS].to_numpy(dtype=np.float32)
    if not np.isfinite(values).all():
        raise ValueError("Static feature cache contains NaN or infinite values.")
    if (values < 0).any():
        raise ValueError("Static feature cache contains negative count/proxy values.")

    return static_checked.set_index(config.source_id_column, drop=True)


def _prepare_dataset_and_static_lookup(
    normalized_frame: pd.DataFrame,
    static_features_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    config: Exp1Config,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Attach the frozen manifest and validate the aligned static feature cache."""
    assert_manifest_integrity(
        manifest,
        config=SplitConfig(
            n_splits=config.n_splits,
            random_state=config.random_state,
            source_id_column=config.source_id_column,
            label_column=config.label_column,
            group_column=config.project_column,
        ),
    )

    dataset = apply_manifest(
        normalized_frame,
        manifest,
        source_id_column=config.source_id_column,
    )
    dataset = _validate_dataset_with_folds(dataset, config)

    static_lookup = _validate_static_feature_frame(static_features_frame, config)

    dataset_ids = pd.Index(dataset[config.source_id_column])
    static_ids = static_lookup.index

    missing_static = dataset_ids.difference(static_ids)
    unexpected_static = static_ids.difference(dataset_ids)

    if len(missing_static) or len(unexpected_static):
        raise ValueError(
            "Static feature cache IDs do not exactly match the normalized dataset. "
            f"missing={len(missing_static):,}, unexpected={len(unexpected_static):,}."
        )

    for fold_id in range(config.n_splits):
        held_out_projects = set(
            dataset.loc[
                dataset[config.fold_column] == fold_id,
                config.project_column,
            ]
        )
        train_projects = set(
            dataset.loc[
                dataset[config.fold_column] != fold_id,
                config.project_column,
            ]
        )
        overlap = held_out_projects.intersection(train_projects)
        if overlap:
            raise RuntimeError(
                f"Project leakage detected in fold {fold_id}; "
                f"examples: {sorted(overlap)[:10]}"
            )

    return dataset, static_lookup


def _build_word_vectorizer(config: Exp1Config) -> TfidfVectorizer:
    return TfidfVectorizer(
        analyzer="word",
        token_pattern=r"(?u)\b\w+\b",
        ngram_range=config.word_ngram_range,
        min_df=config.word_min_df,
        max_df=config.word_max_df,
        max_features=config.word_max_features,
        lowercase=config.lowercase,
        sublinear_tf=config.sublinear_tf,
        norm=config.tfidf_norm,
        dtype=np.float32,
    )


def _build_char_vectorizer(config: Exp1Config) -> TfidfVectorizer:
    return TfidfVectorizer(
        analyzer=config.char_analyzer,
        ngram_range=config.char_ngram_range,
        min_df=config.char_min_df,
        max_df=config.char_max_df,
        max_features=config.char_max_features,
        lowercase=config.lowercase,
        sublinear_tf=config.sublinear_tf,
        norm=config.tfidf_norm,
        dtype=np.float32,
    )


def _fit_lexical_matrices(
    train_code: pd.Series,
    test_code: pd.Series,
    config: Exp1Config,
    fold_id: int,
):
    """Fit train-only TF-IDF matrices and return joined sparse lexical features."""
    label = f"Fold {fold_id + 1}/{config.n_splits}"

    word_vectorizer = _build_word_vectorizer(config)
    char_vectorizer = _build_char_vectorizer(config)

    _log(f"{label} | fitting word TF-IDF...", config.verbose)
    start = time.perf_counter()
    x_train_word = word_vectorizer.fit_transform(train_code)
    x_test_word = word_vectorizer.transform(test_code)
    word_seconds = float(time.perf_counter() - start)
    _log(
        f"{label} | word TF-IDF done in {_format_seconds(word_seconds)} "
        f"({x_train_word.shape[1]:,} features).",
        config.verbose,
    )

    _log(f"{label} | fitting character TF-IDF...", config.verbose)
    start = time.perf_counter()
    x_train_char = char_vectorizer.fit_transform(train_code)
    x_test_char = char_vectorizer.transform(test_code)
    char_seconds = float(time.perf_counter() - start)
    _log(
        f"{label} | character TF-IDF done in {_format_seconds(char_seconds)} "
        f"({x_train_char.shape[1]:,} features).",
        config.verbose,
    )

    _log(f"{label} | joining sparse lexical matrices...", config.verbose)
    start = time.perf_counter()
    x_train_lexical = hstack(
        [x_train_word, x_train_char],
        format="csr",
        dtype=np.float32,
    )
    x_test_lexical = hstack(
        [x_test_word, x_test_char],
        format="csr",
        dtype=np.float32,
    )
    sparse_join_seconds = float(time.perf_counter() - start)

    metadata = {
        "word_features": int(x_train_word.shape[1]),
        "char_features": int(x_train_char.shape[1]),
        "lexical_features": int(x_train_lexical.shape[1]),
        "word_tfidf_seconds": word_seconds,
        "char_tfidf_seconds": char_seconds,
        "sparse_join_seconds": sparse_join_seconds,
        "vectorization_seconds": float(
            word_seconds + char_seconds + sparse_join_seconds
        ),
    }

    _log(
        f"{label} | sparse lexical matrix ready in "
        f"{_format_seconds(sparse_join_seconds)} "
        f"({metadata['lexical_features']:,} columns).",
        config.verbose,
    )

    return x_train_lexical, x_test_lexical, metadata


def _fit_and_transform_svd(
    x_train_lexical,
    x_test_lexical,
    config: Exp1Config,
    fold_id: int,
) -> tuple[np.ndarray, np.ndarray, float, float]:
    """Fit train-only TruncatedSVD and transform train/test lexical features."""
    if config.svd_n_components >= x_train_lexical.shape[1]:
        raise ValueError(
            "svd_n_components must be lower than lexical feature count; "
            f"received {config.svd_n_components} for "
            f"{x_train_lexical.shape[1]} lexical features."
        )

    label = f"Fold {fold_id + 1}/{config.n_splits}"
    svd = TruncatedSVD(
        n_components=config.svd_n_components,
        algorithm=config.svd_algorithm,
        n_iter=config.svd_n_iter,
        n_oversamples=config.svd_n_oversamples,
        random_state=config.random_state,
    )

    _log(
        f"{label} | fitting train-only TruncatedSVD "
        f"({config.svd_n_components} components)...",
        config.verbose,
    )
    start = time.perf_counter()
    x_train_svd = svd.fit_transform(x_train_lexical)
    x_test_svd = svd.transform(x_test_lexical)
    svd_seconds = float(time.perf_counter() - start)

    x_train_svd = np.asarray(x_train_svd, dtype=np.float32)
    x_test_svd = np.asarray(x_test_svd, dtype=np.float32)
    explained_variance = float(np.sum(svd.explained_variance_ratio_))

    _log(
        f"{label} | TruncatedSVD done in {_format_seconds(svd_seconds)} "
        f"(explained variance ratio sum={explained_variance:.4f}).",
        config.verbose,
    )
    return x_train_svd, x_test_svd, svd_seconds, explained_variance


def _get_static_matrix(
    static_lookup: pd.DataFrame,
    source_ids: pd.Series,
    config: Exp1Config,
) -> np.ndarray:
    """Fetch cached static features in exactly the requested source-ID order."""
    matrix = static_lookup.loc[
        pd.Index(source_ids),
        FEATURE_COLUMNS,
    ].to_numpy(dtype=np.float32, copy=True)

    if matrix.shape[1] != len(FEATURE_COLUMNS):
        raise RuntimeError("Static feature matrix has an unexpected column count.")
    if not np.isfinite(matrix).all():
        raise RuntimeError("Static feature matrix contains NaN or infinite values.")
    return matrix


def _build_model(config: Exp1Config) -> RandomForestClassifier:
    return RandomForestClassifier(
        n_estimators=config.rf_n_estimators,
        criterion=config.rf_criterion,
        max_depth=config.rf_max_depth,
        min_samples_split=config.rf_min_samples_split,
        min_samples_leaf=config.rf_min_samples_leaf,
        max_features=config.rf_max_features,
        bootstrap=config.rf_bootstrap,
        max_samples=config.rf_max_samples,
        class_weight=config.rf_class_weight,
        n_jobs=config.rf_n_jobs,
        oob_score=config.rf_oob_score,
        random_state=config.random_state,
    )



def _oob_threshold_candidates(config: Exp1Config) -> np.ndarray:
    """Return a fixed, predeclared threshold grid for OOB F1 selection."""
    grid = np.arange(
        config.oob_threshold_min,
        config.oob_threshold_max + (config.oob_threshold_step / 2.0),
        config.oob_threshold_step,
        dtype=float,
    )
    return np.clip(grid, 0.0, 1.0)


def _binary_metrics_from_decisions(
    labels: Sequence[int] | np.ndarray | pd.Series,
    scores: Sequence[float] | np.ndarray | pd.Series,
    decisions: Sequence[int] | np.ndarray | pd.Series,
    threshold: float | None,
) -> dict:
    """Compute ranking and operating-point metrics from supplied decisions."""
    y_true = np.asarray(labels, dtype=np.int8)
    y_score = np.asarray(scores, dtype=float)
    y_pred = np.asarray(decisions, dtype=np.int8)

    if len(y_true) == 0 or not (len(y_true) == len(y_score) == len(y_pred)):
        raise ValueError("labels, scores, and decisions must be aligned and non-empty.")
    if not np.isin(y_true, [0, 1]).all() or not np.isin(y_pred, [0, 1]).all():
        raise ValueError("labels and decisions must be binary.")

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)

    denominator_npv = tn + fn
    npv = float(tn / denominator_npv) if denominator_npv else 0.0
    return {
        "n_samples": int(len(y_true)),
        "vulnerable_1": int((y_true == 1).sum()),
        "non_vulnerable_0": int((y_true == 0).sum()),
        "positive_rate": float(y_true.mean()),
        "threshold": None if threshold is None else float(threshold),
        "average_precision_pr_auc": float(average_precision_score(y_true, y_score)),
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
        "mcc": float(matthews_corrcoef(y_true, y_pred)),
        "specificity": float(tn / (tn + fp)) if (tn + fp) else 0.0,
        "negative_predictive_value": npv,
        "false_positive_rate": float(fp / (fp + tn)) if (fp + tn) else 0.0,
        "false_negative_rate": float(fn / (fn + tp)) if (fn + tp) else 0.0,
        "true_negative": int(tn),
        "false_positive": int(fp),
        "false_negative": int(fn),
        "true_positive": int(tp),
        "predicted_positive": int(y_pred.sum()),
        "predicted_positive_rate": float(y_pred.mean()),
    }


def _select_oob_threshold(
    labels: np.ndarray,
    oob_scores: np.ndarray,
    config: Exp1Config,
) -> tuple[float, dict]:
    """Choose a threshold from OOB train scores only, maximizing F1 on a fixed grid."""
    valid = np.isfinite(oob_scores) & (oob_scores >= 0.0) & (oob_scores <= 1.0)
    if valid.sum() != len(labels):
        raise RuntimeError(
            "OOB decision scores are incomplete. Increase tree count or inspect RF setup."
        )

    candidates = _oob_threshold_candidates(config)
    rows = []
    best = None
    for threshold in candidates:
        decisions = (oob_scores >= threshold).astype(np.int8)
        metrics = _binary_metrics_from_decisions(
            labels=labels,
            scores=oob_scores,
            decisions=decisions,
            threshold=float(threshold),
        )
        rows.append(metrics)
        # Tie-break: higher precision, then fewer alerts. This is deterministic.
        key = (metrics["f1"], metrics["precision"], -metrics["predicted_positive"])
        if best is None or key > best[0]:
            best = (key, metrics)

    assert best is not None
    summary = dict(best[1])
    summary["selection_source"] = "training_oob_predictions"
    summary["selection_objective"] = config.oob_threshold_objective
    summary["candidate_count"] = int(len(candidates))
    summary["candidate_min"] = float(candidates.min())
    summary["candidate_max"] = float(candidates.max())
    return float(summary["threshold"]), summary


def _evaluate_foldwise_oob_thresholds(predictions: pd.DataFrame) -> dict:
    """Evaluate decisions generated with per-fold OOB-selected thresholds."""
    required = {"fold", "label", "y_score", "y_pred_oob_threshold", "selected_oob_threshold"}
    missing = required.difference(predictions.columns)
    if missing:
        raise KeyError(f"Missing OOB operating-point columns: {sorted(missing)}")

    fold_rows = []
    for fold_id, group in predictions.groupby("fold", sort=True):
        metric = _binary_metrics_from_decisions(
            labels=group["label"],
            scores=group["y_score"],
            decisions=group["y_pred_oob_threshold"],
            threshold=float(group["selected_oob_threshold"].iloc[0]),
        )
        metric["fold"] = int(fold_id)
        metric["test_unique_projects"] = int(group["project"].nunique())
        fold_rows.append(metric)

    fold_metrics = pd.DataFrame(fold_rows).sort_values("fold").reset_index(drop=True)
    pooled_metrics = _binary_metrics_from_decisions(
        labels=predictions["label"],
        scores=predictions["y_score"],
        decisions=predictions["y_pred_oob_threshold"],
        threshold=None,
    )
    pooled_metrics["threshold_strategy"] = "per_fold_training_oob_f1"
    pooled_metrics["selected_threshold_min"] = float(predictions["selected_oob_threshold"].min())
    pooled_metrics["selected_threshold_max"] = float(predictions["selected_oob_threshold"].max())
    pooled_metrics["selected_threshold_mean"] = float(predictions["selected_oob_threshold"].mean())

    summary_rows = []
    metric_columns = [
        "average_precision_pr_auc", "precision", "recall", "f1", "mcc",
        "false_positive_rate", "predicted_positive_rate", "threshold",
    ]
    for column in metric_columns:
        series = fold_metrics[column].astype(float)
        summary_rows.append({
            "metric": column,
            "mean": float(series.mean()),
            "std": float(series.std(ddof=1)),
            "min": float(series.min()),
            "max": float(series.max()),
        })
    return {
        "pooled_metrics": pooled_metrics,
        "fold_metrics": fold_metrics,
        "fold_summary": pd.DataFrame(summary_rows),
    }

def _feature_importance_frame(
    model: RandomForestClassifier,
    fold_id: int,
    config: Exp1Config,
) -> pd.DataFrame:
    """Return all RF impurity importances; static features remain human-readable."""
    component_names = [
        f"svd_component_{index:03d}"
        for index in range(config.svd_n_components)
    ]
    static_names = [f"static::{name}" for name in FEATURE_COLUMNS]
    names = component_names + static_names

    values = np.asarray(model.feature_importances_, dtype=float)
    if len(values) != len(names):
        raise RuntimeError(
            "Feature-importance length mismatch: "
            f"{len(values)} values for {len(names)} expected names."
        )

    frame = pd.DataFrame(
        {
            "fold": int(fold_id),
            "feature": names,
            "feature_group": (
                ["svd_component"] * len(component_names)
                + ["static"] * len(static_names)
            ),
            "importance": values,
        }
    )
    frame["rank"] = (
        frame["importance"]
        .rank(ascending=False, method="first")
        .astype(int)
    )
    return frame.sort_values("rank").reset_index(drop=True)


def _run_single_fold(
    train_frame: pd.DataFrame,
    test_frame: pd.DataFrame,
    static_lookup: pd.DataFrame,
    fold_id: int,
    config: Exp1Config,
) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    """Fit one EXP-1 fold and return held-out predictions, importances, and timing."""
    label = f"Fold {fold_id + 1}/{config.n_splits}"
    started = time.perf_counter()

    _log(
        f"{label} started | train={len(train_frame):,}, test={len(test_frame):,}, "
        f"train projects={train_frame[config.project_column].nunique():,}, "
        f"test projects={test_frame[config.project_column].nunique():,}.",
        config.verbose,
    )

    x_train_lexical, x_test_lexical, lexical_metadata = _fit_lexical_matrices(
        train_code=train_frame[config.code_column],
        test_code=test_frame[config.code_column],
        config=config,
        fold_id=fold_id,
    )

    x_train_svd, x_test_svd, svd_seconds, svd_variance_ratio = (
        _fit_and_transform_svd(
            x_train_lexical=x_train_lexical,
            x_test_lexical=x_test_lexical,
            config=config,
            fold_id=fold_id,
        )
    )

    _log(f"{label} | loading cached static features...", config.verbose)
    static_start = time.perf_counter()
    x_train_static = _get_static_matrix(
        static_lookup,
        train_frame[config.source_id_column],
        config,
    )
    x_test_static = _get_static_matrix(
        static_lookup,
        test_frame[config.source_id_column],
        config,
    )
    static_seconds = float(time.perf_counter() - static_start)

    _log(f"{label} | combining SVD and static features...", config.verbose)
    concatenate_start = time.perf_counter()
    x_train = np.hstack([x_train_svd, x_train_static]).astype(
        np.float32,
        copy=False,
    )
    x_test = np.hstack([x_test_svd, x_test_static]).astype(
        np.float32,
        copy=False,
    )
    concatenate_seconds = float(time.perf_counter() - concatenate_start)

    expected_dense_features = config.svd_n_components + len(FEATURE_COLUMNS)
    if x_train.shape[1] != expected_dense_features:
        raise RuntimeError(
            f"Expected {expected_dense_features} final features; "
            f"received {x_train.shape[1]}."
        )

    y_train = train_frame[config.label_column].to_numpy(dtype=np.int8)
    model = _build_model(config)

    _log(
        f"{label} | training Random Forest "
        f"(trees={config.rf_n_estimators}, max_features={config.rf_max_features}, "
        f"class_weight={config.rf_class_weight})...",
        config.verbose,
    )
    fit_start = time.perf_counter()
    model.fit(x_train, y_train)
    model_fit_seconds = float(time.perf_counter() - fit_start)
    _log(
        f"{label} | Random Forest done in {_format_seconds(model_fit_seconds)}.",
        config.verbose,
    )

    positive_index = np.where(model.classes_ == 1)[0]
    if len(positive_index) != 1:
        raise RuntimeError("Random Forest does not expose positive class label 1.")
    positive_index = int(positive_index[0])

    _log(
        f"{label} | selecting threshold from training-only OOB predictions...",
        config.verbose,
    )
    oob_start = time.perf_counter()
    if not hasattr(model, "oob_decision_function_"):
        raise RuntimeError("RF OOB predictions are unavailable; set rf_oob_score=True.")
    oob_scores = np.asarray(
        model.oob_decision_function_[:, positive_index],
        dtype=np.float64,
    )
    selected_threshold, oob_threshold_metrics = _select_oob_threshold(
        labels=y_train,
        oob_scores=oob_scores,
        config=config,
    )
    oob_selection_seconds = float(time.perf_counter() - oob_start)
    _log(
        f"{label} | OOB F1 threshold={selected_threshold:.3f} "
        f"(OOB F1={oob_threshold_metrics['f1']:.4f}).",
        config.verbose,
    )

    _log(f"{label} | scoring held-out projects...", config.verbose)
    prediction_start = time.perf_counter()
    y_score = model.predict_proba(x_test)[:, positive_index]
    y_pred_oob_threshold = (y_score >= selected_threshold).astype(np.int8)
    prediction_seconds = float(time.perf_counter() - prediction_start)

    predictions = test_frame[
        [
            config.source_id_column,
            config.fold_column,
            config.label_column,
            config.project_column,
        ]
    ].copy().rename(
        columns={
            config.source_id_column: "source_row_id",
            config.fold_column: "fold",
            config.label_column: "label",
            config.project_column: "project",
        }
    )
    predictions["y_score"] = y_score.astype(np.float64)
    predictions["selected_oob_threshold"] = float(selected_threshold)
    predictions["y_pred_oob_threshold"] = y_pred_oob_threshold.astype(np.int8)

    importances = _feature_importance_frame(
        model=model,
        fold_id=fold_id,
        config=config,
    )

    total_seconds = float(time.perf_counter() - started)
    metadata = {
        "fold": int(fold_id),
        "train_rows": int(len(train_frame)),
        "test_rows": int(len(test_frame)),
        "train_vulnerable": int((train_frame[config.label_column] == 1).sum()),
        "test_vulnerable": int((test_frame[config.label_column] == 1).sum()),
        "train_positive_rate": float(train_frame[config.label_column].mean()),
        "test_positive_rate": float(test_frame[config.label_column].mean()),
        "train_unique_projects": int(train_frame[config.project_column].nunique()),
        "test_unique_projects": int(test_frame[config.project_column].nunique()),
        **lexical_metadata,
        "svd_components": int(config.svd_n_components),
        "svd_seconds": float(svd_seconds),
        "svd_explained_variance_ratio_sum": float(svd_variance_ratio),
        "static_features": int(len(FEATURE_COLUMNS)),
        "static_lookup_seconds": float(static_seconds),
        "dense_feature_concatenation_seconds": float(concatenate_seconds),
        "final_dense_features": int(expected_dense_features),
        "model_fit_seconds": float(model_fit_seconds),
        "oob_threshold_selection_seconds": float(oob_selection_seconds),
        "selected_oob_threshold": float(selected_threshold),
        "oob_average_precision_pr_auc": float(oob_threshold_metrics["average_precision_pr_auc"]),
        "oob_precision": float(oob_threshold_metrics["precision"]),
        "oob_recall": float(oob_threshold_metrics["recall"]),
        "oob_f1": float(oob_threshold_metrics["f1"]),
        "oob_mcc": float(oob_threshold_metrics["mcc"]),
        "prediction_seconds": float(prediction_seconds),
        "total_fold_seconds": float(total_seconds),
        "optimizer": "RandomForestClassifier",
        "score_min": float(np.min(y_score)),
        "score_max": float(np.max(y_score)),
        "score_mean": float(np.mean(y_score)),
    }

    _log(
        f"{label} completed in {_format_seconds(total_seconds)}.",
        config.verbose,
    )

    del (
        x_train_lexical,
        x_test_lexical,
        x_train_svd,
        x_test_svd,
        x_train_static,
        x_test_static,
        x_train,
        x_test,
        model,
    )
    gc.collect()

    return predictions, importances, metadata


def run_exp1_profile_fold(
    normalized_frame: pd.DataFrame,
    static_features_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    fold_id: int = 0,
    config: Exp1Config = Exp1Config(),
) -> dict:
    """
    Run one fold only for computational feasibility validation.

    The returned thresholded metrics use a threshold selected solely from
    training-partition OOB predictions. They remain descriptive for one outer
    fold and are not the official five-fold EXP-1 result.
    """
    _validate_config(config)
    if fold_id not in range(config.n_splits):
        raise ValueError(
            f"fold_id must be in [0, {config.n_splits - 1}], got {fold_id}."
        )

    _log(
        f"CS1-EXP1 profiling mode: running Fold {fold_id + 1}/{config.n_splits} only.",
        config.verbose,
    )

    dataset, static_lookup = _prepare_dataset_and_static_lookup(
        normalized_frame=normalized_frame,
        static_features_frame=static_features_frame,
        manifest=manifest,
        config=config,
    )

    train_frame = dataset.loc[
        dataset[config.fold_column] != fold_id
    ].reset_index(drop=True)
    test_frame = dataset.loc[
        dataset[config.fold_column] == fold_id
    ].reset_index(drop=True)

    predictions, importances, metadata = _run_single_fold(
        train_frame=train_frame,
        test_frame=test_frame,
        static_lookup=static_lookup,
        fold_id=fold_id,
        config=config,
    )

    selected_threshold = float(predictions["selected_oob_threshold"].iloc[0])
    metrics = _binary_metrics_from_decisions(
        labels=predictions["label"],
        scores=predictions["y_score"],
        decisions=predictions["y_pred_oob_threshold"],
        threshold=selected_threshold,
    )
    metrics["threshold_strategy"] = "training_oob_f1"
    default_threshold_metrics = compute_binary_metrics(
        labels=predictions["label"],
        scores=predictions["y_score"],
        threshold=config.decision_threshold,
    )

    _log(
        "Profiling run complete. These metrics are descriptive for one fold only; "
        "do not treat them as the official five-fold EXP-1 result.",
        config.verbose,
    )

    del train_frame, test_frame, dataset, static_lookup
    gc.collect()

    return {
        "fold_id": int(fold_id),
        "predictions": predictions,
        "feature_importances": importances,
        "training_metadata": pd.DataFrame([metadata]),
        "profile_metrics": metrics,
        "default_threshold_metrics": default_threshold_metrics,
    }


def _save_exp1_artifacts(
    results: Mapping[str, object],
    output_dir: Path | str,
    config: Exp1Config,
    additional_metadata: Optional[Mapping[str, object]] = None,
) -> Exp1Artifacts:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    oof_predictions = results["oof_predictions"]
    fold_training = results["fold_training"]
    feature_importances = results["feature_importances"]
    evaluation = results["evaluation"]
    oob_operating_evaluation = results["oob_operating_evaluation"]

    if not isinstance(oof_predictions, pd.DataFrame):
        raise TypeError("oof_predictions must be a DataFrame.")
    if not isinstance(fold_training, pd.DataFrame):
        raise TypeError("fold_training must be a DataFrame.")
    if not isinstance(feature_importances, pd.DataFrame):
        raise TypeError("feature_importances must be a DataFrame.")
    if not isinstance(evaluation, Mapping):
        raise TypeError("evaluation must be a mapping.")
    if not isinstance(oob_operating_evaluation, Mapping):
        raise TypeError("oob_operating_evaluation must be a mapping.")

    safe_name = "".join(
        char if char.isalnum() or char in {"_", "-"} else "_"
        for char in config.experiment_name.strip().lower().replace(" ", "_")
    )

    config_json = output_dir / f"{safe_name}_config.json"
    fold_training_csv = output_dir / f"{safe_name}_fold_training.csv"
    feature_importances_csv = output_dir / f"{safe_name}_feature_importances.csv"
    static_feature_importances_csv = (
        output_dir / f"{safe_name}_static_feature_importances.csv"
    )
    oob_operating_metrics_json = (
        output_dir / f"{safe_name}_oob_operating_pooled_metrics.json"
    )
    oob_operating_fold_metrics_csv = (
        output_dir / f"{safe_name}_oob_operating_fold_metrics.csv"
    )
    oob_operating_fold_summary_csv = (
        output_dir / f"{safe_name}_oob_operating_fold_summary.csv"
    )
    run_metadata_json = output_dir / f"{safe_name}_run_metadata.json"

    with config_json.open("w", encoding="utf-8") as file:
        json.dump(
            {"exp1_version": EXP1_VERSION, "config": asdict(config)},
            file,
            indent=2,
        )

    fold_training.to_csv(fold_training_csv, index=False)
    feature_importances.to_csv(feature_importances_csv, index=False)

    static_importances = (
        feature_importances.loc[
            feature_importances["feature_group"] == "static"
        ]
        .sort_values(["fold", "rank"])
        .reset_index(drop=True)
    )
    static_importances.to_csv(static_feature_importances_csv, index=False)

    with oob_operating_metrics_json.open("w", encoding="utf-8") as file:
        json.dump(oob_operating_evaluation["pooled_metrics"], file, indent=2)
    oob_operating_evaluation["fold_metrics"].to_csv(
        oob_operating_fold_metrics_csv,
        index=False,
    )
    oob_operating_evaluation["fold_summary"].to_csv(
        oob_operating_fold_summary_csv,
        index=False,
    )

    evaluation_paths = save_evaluation_artifacts(
        evaluation=evaluation,
        output_dir=output_dir,
        experiment_name=config.experiment_name,
        config=EvaluationConfig(
            threshold=config.decision_threshold,
            expected_n_folds=config.n_splits,
        ),
        additional_metadata={
            "exp1_version": EXP1_VERSION,
            "model": (
                "RandomForestClassifier over train-only TruncatedSVD lexical "
                "features plus deterministic static source-level proxy features"
            ),
            "lexical_representation": (
                "word TF-IDF ngrams (1,3) + character TF-IDF ngrams (3,4)"
            ),
            "static_feature_count": int(len(FEATURE_COLUMNS)),
            "final_dense_feature_count": int(
                config.svd_n_components + len(FEATURE_COLUMNS)
            ),
            "score_interpretation": (
                "Random Forest positive-class score; not a calibrated "
                "real-world vulnerability probability."
            ),
            "operating_threshold_strategy": (
                "Per-fold threshold selected by maximum F1 on training-only "
                "out-of-bag predictions over a fixed grid from 0.005 to 0.250."
            ),
            "importance_note": (
                "Random Forest impurity importances are descriptive diagnostics, "
                "not causal explanations."
            ),
            **dict(additional_metadata or {}),
        },
    )

    run_metadata = {
        "exp1_version": EXP1_VERSION,
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "experiment_name": config.experiment_name,
        "config": asdict(config),
        "n_oof_predictions": int(len(oof_predictions)),
        "folds_completed": sorted(
            oof_predictions["fold"].unique().astype(int).tolist()
        ),
        "total_vectorization_seconds": float(
            fold_training["vectorization_seconds"].sum()
        ),
        "total_svd_seconds": float(fold_training["svd_seconds"].sum()),
        "total_model_fit_seconds": float(
            fold_training["model_fit_seconds"].sum()
        ),
        "total_prediction_seconds": float(
            fold_training["prediction_seconds"].sum()
        ),
        "total_runtime_seconds": float(
            fold_training["total_fold_seconds"].sum()
        ),
        "additional_metadata": dict(additional_metadata or {}),
    }
    with run_metadata_json.open("w", encoding="utf-8") as file:
        json.dump(run_metadata, file, indent=2)

    return Exp1Artifacts(
        config_json=config_json,
        fold_training_csv=fold_training_csv,
        feature_importances_csv=feature_importances_csv,
        static_feature_importances_csv=static_feature_importances_csv,
        oob_operating_metrics_json=oob_operating_metrics_json,
        oob_operating_fold_metrics_csv=oob_operating_fold_metrics_csv,
        oob_operating_fold_summary_csv=oob_operating_fold_summary_csv,
        run_metadata_json=run_metadata_json,
        evaluation_paths=evaluation_paths,
    )


def run_exp1(
    normalized_frame: pd.DataFrame,
    static_features_frame: pd.DataFrame,
    manifest: pd.DataFrame,
    config: Exp1Config = Exp1Config(),
    output_dir: Optional[Path | str] = None,
    additional_metadata: Optional[Mapping[str, object]] = None,
) -> dict:
    """
    Run the official five-fold project-aware CS1-EXP1-RF experiment.

    Run ``run_exp1_profile_fold`` first after adding this module to Colab.
    """
    _validate_config(config)
    _log(
        f"CS1-EXP1 official run started: {config.n_splits}-fold grouped CV.",
        config.verbose,
    )
    _log(
        f"Configuration: lexical<= {config.word_max_features + config.char_max_features:,}, "
        f"SVD={config.svd_n_components}, static={len(FEATURE_COLUMNS)}, "
        f"RF trees={config.rf_n_estimators}.",
        config.verbose,
    )

    dataset, static_lookup = _prepare_dataset_and_static_lookup(
        normalized_frame=normalized_frame,
        static_features_frame=static_features_frame,
        manifest=manifest,
        config=config,
    )

    prediction_frames: list[pd.DataFrame] = []
    importance_frames: list[pd.DataFrame] = []
    training_rows: list[dict] = []

    run_started = time.perf_counter()

    for fold_id in range(config.n_splits):
        train_frame = dataset.loc[
            dataset[config.fold_column] != fold_id
        ].reset_index(drop=True)
        test_frame = dataset.loc[
            dataset[config.fold_column] == fold_id
        ].reset_index(drop=True)

        if train_frame.empty or test_frame.empty:
            raise RuntimeError(f"Fold {fold_id} has an empty partition.")
        if set(test_frame[config.label_column].unique().tolist()) != {0, 1}:
            raise RuntimeError(f"Fold {fold_id} does not contain both classes.")

        predictions, importances, metadata = _run_single_fold(
            train_frame=train_frame,
            test_frame=test_frame,
            static_lookup=static_lookup,
            fold_id=fold_id,
            config=config,
        )
        prediction_frames.append(predictions)
        importance_frames.append(importances)
        training_rows.append(metadata)

        del train_frame, test_frame
        gc.collect()

    oof_predictions = (
        pd.concat(prediction_frames, ignore_index=True)
        .sort_values("source_row_id", kind="stable")
        .reset_index(drop=True)
    )
    feature_importances = (
        pd.concat(importance_frames, ignore_index=True)
        .sort_values(["fold", "rank"])
        .reset_index(drop=True)
    )
    fold_training = pd.DataFrame(training_rows).sort_values("fold").reset_index(drop=True)

    if len(oof_predictions) != len(dataset):
        raise RuntimeError(
            "OOF prediction count does not match dataset rows: "
            f"{len(oof_predictions):,} vs {len(dataset):,}."
        )
    if oof_predictions["source_row_id"].duplicated().any():
        raise RuntimeError("Duplicate source_row_id detected in OOF predictions.")

    # This standard evaluation retains PR curves and a fixed 0.50 diagnostic.
    # EXP-1's primary thresholded operating metrics are stored separately below,
    # using per-fold thresholds selected only from training OOB predictions.
    evaluation = evaluate_oof_predictions(
        oof_predictions,
        config=EvaluationConfig(
            threshold=config.decision_threshold,
            expected_n_folds=config.n_splits,
        ),
    )
    oob_operating_evaluation = _evaluate_foldwise_oob_thresholds(
        oof_predictions
    )

    total_runtime_seconds = float(time.perf_counter() - run_started)
    _log(
        f"CS1-EXP1 official run completed in {_format_seconds(total_runtime_seconds)}.",
        config.verbose,
    )

    results = {
        "oof_predictions": evaluation["predictions"],
        "feature_importances": feature_importances,
        "fold_training": fold_training,
        "evaluation": evaluation,
        "oob_operating_evaluation": oob_operating_evaluation,
        "total_runtime_seconds": total_runtime_seconds,
    }

    if output_dir is not None:
        results["artifacts"] = _save_exp1_artifacts(
            results=results,
            output_dir=output_dir,
            config=config,
            additional_metadata=additional_metadata,
        )
        _log(f"Artifacts saved to: {Path(output_dir)}", config.verbose)

    return results


__all__ = [
    "EXP1_VERSION",
    "Exp1Artifacts",
    "Exp1Config",
    "run_exp1",
    "run_exp1_profile_fold",
]
