"""
Within-project StratifiedKFold manifest utilities for Case Study 1.

Purpose
-------
This module creates a SECOND, explicitly labelled evaluation protocol:

    StratifiedKFold (randomized)
    - preserves vulnerable/non-vulnerable class proportions;
    - permits the same software project to occur in training and test folds;
    - measures performance when the model has access to functions from the
      same project ecosystems during training.

It must NOT replace the primary project-grouped manifest. The grouped manifest
measures unseen-project generalization; this manifest measures within-project
generalization. The two result sets must always be reported separately.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from hashlib import sha256
import json
from pathlib import Path
from typing import Iterable, Optional

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold


MANIFEST_VERSION = "cs1-within-project-stratified-5fold-v1"
DEFAULT_N_SPLITS = 5
DEFAULT_RANDOM_STATE = 42
REQUIRED_COLUMNS = ("source_row_id", "label", "project")


@dataclass(frozen=True)
class WithinProjectSplitConfig:
    """Configuration for the secondary within-project StratifiedKFold protocol."""

    n_splits: int = DEFAULT_N_SPLITS
    random_state: int = DEFAULT_RANDOM_STATE
    shuffle: bool = True
    source_id_column: str = "source_row_id"
    label_column: str = "label"
    project_column: str = "project"


@dataclass(frozen=True)
class WithinProjectManifestPaths:
    """Locations of artifacts generated by ``save_within_project_manifest_artifacts``."""

    csv_path: Path
    parquet_path: Path
    summary_path: Path
    metadata_path: Path


def _require_columns(frame: pd.DataFrame, columns: Iterable[str]) -> None:
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        raise KeyError(
            f"Missing required column(s): {missing}. "
            f"Available columns: {sorted(frame.columns.tolist())}"
        )


def _prepare_split_frame(
    frame: pd.DataFrame,
    config: WithinProjectSplitConfig,
) -> pd.DataFrame:
    _require_columns(
        frame,
        [
            config.source_id_column,
            config.label_column,
            config.project_column,
        ],
    )

    split_frame = frame[
        [
            config.source_id_column,
            config.label_column,
            config.project_column,
        ]
    ].copy().rename(
        columns={
            config.source_id_column: "source_row_id",
            config.label_column: "label",
            config.project_column: "project",
        }
    )

    if split_frame["source_row_id"].isna().any():
        raise ValueError("source_row_id contains missing values.")
    if split_frame["source_row_id"].duplicated().any():
        raise ValueError("source_row_id must uniquely identify every sample.")

    labels = pd.to_numeric(split_frame["label"], errors="raise")
    if not labels.isin([0, 1]).all():
        raise ValueError("Case Study 1 requires binary labels 0 and 1.")
    if labels.nunique() != 2:
        raise ValueError("Both classes are required for StratifiedKFold.")
    split_frame["label"] = labels.astype("int8")

    if split_frame["project"].isna().any():
        raise ValueError("project contains missing values.")
    split_frame["project"] = split_frame["project"].astype(str).str.strip()
    if (split_frame["project"] == "").any():
        raise ValueError("project contains empty identifiers.")

    class_counts = split_frame["label"].value_counts()
    if int(class_counts.min()) < config.n_splits:
        raise ValueError(
            "The least frequent class has fewer samples than n_splits; "
            "StratifiedKFold cannot create all folds."
        )
    return split_frame


def dataset_split_fingerprint(
    frame: pd.DataFrame,
    config: WithinProjectSplitConfig = WithinProjectSplitConfig(),
) -> str:
    """Fingerprint row IDs, labels, and project values for manifest traceability."""
    split_frame = _prepare_split_frame(frame, config)
    stable = split_frame.sort_values("source_row_id", kind="stable").reset_index(drop=True)
    row_hashes = pd.util.hash_pandas_object(
        stable[["source_row_id", "label", "project"]],
        index=False,
    ).values
    return sha256(row_hashes.tobytes()).hexdigest()


def create_within_project_stratified_manifest(
    frame: pd.DataFrame,
    config: WithinProjectSplitConfig = WithinProjectSplitConfig(),
) -> pd.DataFrame:
    """
    Create a fixed randomized StratifiedKFold test-fold assignment.

    The output has the same schema as the grouped manifest:
    source_row_id, label, project, fold.

    Project overlap is deliberately allowed and expected under this protocol.
    """
    split_frame = _prepare_split_frame(frame, config)
    splitter = StratifiedKFold(
        n_splits=config.n_splits,
        shuffle=config.shuffle,
        random_state=config.random_state if config.shuffle else None,
    )

    folds = np.full(len(split_frame), fill_value=-1, dtype=np.int16)

    for fold_id, (_, test_positions) in enumerate(
        splitter.split(
            X=np.zeros((len(split_frame), 1), dtype=np.uint8),
            y=split_frame["label"].to_numpy(),
        )
    ):
        if np.any(folds[test_positions] != -1):
            raise RuntimeError("A row was assigned to multiple test folds.")
        folds[test_positions] = fold_id

    if np.any(folds == -1):
        raise RuntimeError("Some rows were not assigned to a test fold.")

    manifest = split_frame.copy()
    manifest["fold"] = folds.astype(int)

    assert_within_project_manifest_integrity(manifest, config=config)
    return manifest


def summarize_within_project_manifest(
    manifest: pd.DataFrame,
    config: WithinProjectSplitConfig = WithinProjectSplitConfig(),
) -> pd.DataFrame:
    """Return fold balance and deliberate project-overlap diagnostics."""
    _require_columns(manifest, ("source_row_id", "label", "project", "fold"))

    global_positive_rate = float(pd.to_numeric(manifest["label"]).mean())
    total_rows = len(manifest)
    total_projects = int(manifest["project"].nunique())

    rows = []
    for fold_id in range(config.n_splits):
        test_frame = manifest.loc[manifest["fold"] == fold_id]
        train_frame = manifest.loc[manifest["fold"] != fold_id]

        test_projects = set(test_frame["project"])
        train_projects = set(train_frame["project"])
        overlap = test_projects.intersection(train_projects)

        test_project_rows_in_overlap = int(
            test_frame["project"].isin(overlap).sum()
        )

        rows.append(
            {
                "fold": int(fold_id),
                "test_rows": int(len(test_frame)),
                "test_vulnerable": int((test_frame["label"] == 1).sum()),
                "test_non_vulnerable": int((test_frame["label"] == 0).sum()),
                "test_positive_rate": float(test_frame["label"].mean()),
                "positive_rate_delta_from_global": float(
                    test_frame["label"].mean() - global_positive_rate
                ),
                "test_unique_projects": int(test_frame["project"].nunique()),
                "train_rows": int(len(train_frame)),
                "train_unique_projects": int(train_frame["project"].nunique()),
                "train_test_project_overlap": int(len(overlap)),
                "overlap_rate_of_test_projects": float(
                    len(overlap) / max(1, len(test_projects))
                ),
                "test_rows_from_overlapping_projects": test_project_rows_in_overlap,
                "test_row_overlap_rate": float(
                    test_project_rows_in_overlap / max(1, len(test_frame))
                ),
                "test_row_share": float(len(test_frame) / total_rows),
                "test_project_share": float(
                    test_frame["project"].nunique() / max(1, total_projects)
                ),
            }
        )

    return pd.DataFrame(rows).sort_values("fold").reset_index(drop=True)


def assert_within_project_manifest_integrity(
    manifest: pd.DataFrame,
    config: WithinProjectSplitConfig = WithinProjectSplitConfig(),
) -> None:
    """
    Validate a within-project StratifiedKFold manifest.

    Unlike the grouped protocol, this deliberately DOES NOT reject project
    overlap. It verifies that rows are assigned exactly once, folds exist,
    class labels are valid, and every held-out fold contains both classes.
    """
    _require_columns(manifest, ("source_row_id", "label", "project", "fold"))

    if manifest.empty:
        raise ValueError("Manifest is empty.")
    if manifest["source_row_id"].isna().any():
        raise ValueError("Manifest contains missing source_row_id values.")
    if manifest["source_row_id"].duplicated().any():
        raise ValueError("Manifest contains duplicate source_row_id values.")

    labels = pd.to_numeric(manifest["label"], errors="raise")
    if not labels.isin([0, 1]).all():
        raise ValueError("Manifest labels must be exactly 0 or 1.")

    folds = pd.to_numeric(manifest["fold"], errors="raise").astype(int)
    expected_folds = set(range(config.n_splits))
    actual_folds = set(folds.unique().tolist())
    if actual_folds != expected_folds:
        raise ValueError(
            f"Expected folds {sorted(expected_folds)}, got {sorted(actual_folds)}."
        )
    if (folds < 0).any() or (folds >= config.n_splits).any():
        raise ValueError("Manifest contains invalid fold IDs.")

    for fold_id in range(config.n_splits):
        test_labels = set(
            manifest.loc[manifest["fold"] == fold_id, "label"].astype(int)
        )
        if test_labels != {0, 1}:
            raise ValueError(
                f"Fold {fold_id} lacks both classes: {sorted(test_labels)}."
            )


def save_within_project_manifest_artifacts(
    manifest: pd.DataFrame,
    output_dir: Path | str,
    config: WithinProjectSplitConfig = WithinProjectSplitConfig(),
    dataset_fingerprint: Optional[str] = None,
    normalized_dataset_path: Optional[Path | str] = None,
) -> WithinProjectManifestPaths:
    """Save manifest, summary, and transparent protocol metadata."""
    assert_within_project_manifest_integrity(manifest, config=config)

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"cs1_within_project_stratified_{config.n_splits}fold"

    csv_path = output_dir / f"{stem}_manifest.csv"
    parquet_path = output_dir / f"{stem}_manifest.parquet"
    summary_path = output_dir / f"{stem}_fold_summary.csv"
    metadata_path = output_dir / f"{stem}_metadata.json"

    manifest_to_save = manifest.sort_values("source_row_id", kind="stable").reset_index(drop=True)
    summary = summarize_within_project_manifest(manifest_to_save, config=config)

    manifest_to_save.to_csv(csv_path, index=False)
    manifest_to_save.to_parquet(parquet_path, index=False)
    summary.to_csv(summary_path, index=False)

    if dataset_fingerprint is None:
        dataset_fingerprint = dataset_split_fingerprint(manifest_to_save, config=config)

    metadata = {
        "manifest_version": MANIFEST_VERSION,
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "evaluation_protocol": "within_project_stratified",
        "splitter": "StratifiedKFold",
        "config": asdict(config),
        "dataset_split_fingerprint": dataset_fingerprint,
        "normalized_dataset_path": (
            str(normalized_dataset_path) if normalized_dataset_path is not None else None
        ),
        "rows": int(len(manifest_to_save)),
        "vulnerable_rows": int((manifest_to_save["label"] == 1).sum()),
        "non_vulnerable_rows": int((manifest_to_save["label"] == 0).sum()),
        "global_positive_rate": float(manifest_to_save["label"].mean()),
        "unique_projects": int(manifest_to_save["project"].nunique()),
        "integrity_checks": {
            "all_rows_assigned_once": True,
            "both_classes_present_in_each_test_fold": True,
            "project_overlap_between_train_and_test": "allowed_and_expected",
        },
        "interpretation_note": (
            "This manifest measures within-project generalization because functions "
            "from a project can appear in both training and held-out folds. It must "
            "not be interpreted as unseen-project performance."
        ),
    }
    with metadata_path.open("w", encoding="utf-8") as file:
        json.dump(metadata, file, indent=2)

    return WithinProjectManifestPaths(
        csv_path=csv_path,
        parquet_path=parquet_path,
        summary_path=summary_path,
        metadata_path=metadata_path,
    )


def load_within_project_manifest(
    manifest_path: Path | str,
    config: WithinProjectSplitConfig = WithinProjectSplitConfig(),
) -> pd.DataFrame:
    """Load and validate a saved within-project manifest."""
    manifest_path = Path(manifest_path)
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")

    if manifest_path.suffix.lower() == ".parquet":
        manifest = pd.read_parquet(manifest_path)
    elif manifest_path.suffix.lower() == ".csv":
        manifest = pd.read_csv(manifest_path)
    else:
        raise ValueError("Manifest must be .csv or .parquet.")

    assert_within_project_manifest_integrity(manifest, config=config)
    return manifest


def apply_manifest(
    frame: pd.DataFrame,
    manifest: pd.DataFrame,
    source_id_column: str = "source_row_id",
) -> pd.DataFrame:
    """Attach a frozen manifest with strict one-to-one data identity checks."""
    _require_columns(frame, (source_id_column,))
    _require_columns(manifest, ("source_row_id", "fold", "label", "project"))

    source = frame.copy()
    if source_id_column != "source_row_id":
        source = source.rename(columns={source_id_column: "source_row_id"})

    if source["source_row_id"].duplicated().any():
        raise ValueError("Input frame has duplicate source_row_id values.")

    merged = source.merge(
        manifest[["source_row_id", "fold", "label", "project"]],
        on="source_row_id",
        how="left",
        validate="one_to_one",
        suffixes=("", "_manifest"),
    )

    if merged["fold"].isna().any():
        raise ValueError(
            f"{int(merged['fold'].isna().sum()):,} rows have no fold assignment."
        )

    if "label_manifest" in merged.columns:
        mismatch = (
            merged["label"].astype(int) != merged["label_manifest"].astype(int)
        )
        if mismatch.any():
            raise ValueError("Label mismatch between dataset and manifest.")
        merged = merged.drop(columns=["label_manifest"])

    if "project_manifest" in merged.columns:
        mismatch = (
            merged["project"].astype(str).str.strip()
            != merged["project_manifest"].astype(str).str.strip()
        )
        if mismatch.any():
            raise ValueError("Project mismatch between dataset and manifest.")
        merged = merged.drop(columns=["project_manifest"])

    merged["fold"] = merged["fold"].astype(int)
    return merged


__all__ = [
    "DEFAULT_N_SPLITS",
    "DEFAULT_RANDOM_STATE",
    "MANIFEST_VERSION",
    "WithinProjectManifestPaths",
    "WithinProjectSplitConfig",
    "apply_manifest",
    "assert_within_project_manifest_integrity",
    "create_within_project_stratified_manifest",
    "dataset_split_fingerprint",
    "load_within_project_manifest",
    "save_within_project_manifest_artifacts",
    "summarize_within_project_manifest",
]
